<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a49f9fb1-8133-4a22-b2a3-bbb9785d28fa-01
 * Migration datetime: 2021-05-17 08:15:59.610409
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01TECD2021051708155961 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tecd_customer_address', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 20)->nullable(true);
            $table->string('salutation', 40)->nullable(true);
            $table->string('name_1', 80)->nullable(true);
            $table->string('name_2', 80)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('country_ident', 10)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->string('contact_person', 80)->nullable(true);
            $table->string('phone', 80)->nullable(true);
            $table->string('email', 240)->nullable(true);
            $table->string('web', 80)->nullable(true);
            $table->string('ticket_email', 240)->nullable(true);
            $table->string('ticket_email_subject', 250)->nullable(true);
            $table->longText('ticket_email_body')->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->float('lat', 12, 7)->nullable(true);
            $table->float('lon', 12, 7)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
        });
        Schema::create('tecd_delivery_address', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('customer_ident', 30)->nullable(true);
            $table->string('ident', 30)->nullable(true);
            $table->string('salutation', 40)->nullable(true);
            $table->string('name_1', 80)->nullable(true);
            $table->string('name_2', 80)->nullable(true);
            $table->string('name_3', 80)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('country_ident', 10)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->string('contact_person', 80)->nullable(true);
            $table->string('phone', 80)->nullable(true);
            $table->string('email', 240)->nullable(true);
            $table->string('web', 80)->nullable(true);
            $table->string('department', 30)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->float('lat', 12, 7)->nullable(true);
            $table->float('lon', 12, 7)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_customer_address_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_system', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('ext_id')->default(0)->unsigned();
            $table->string('serial_number', 80)->nullable(true);
            $table->string('model_ident_1', 60)->nullable(true);
            $table->string('model_ident_2', 60)->nullable(true);
            $table->string('servicecode_ident', 30)->nullable(true);
            $table->string('status_ident', 30)->nullable(true);
            $table->string('priority_ident', 30)->nullable(true);
            $table->string('item_ident', 30)->nullable(true);
            $table->string('vendor_ident', 30)->nullable(true);
            $table->string('vendor_item_ident', 30)->nullable(true);
            $table->string('costcenter_ident', 30)->nullable(true);
            $table->string('location_name_1', 80)->nullable(true);
            $table->string('location_name_2', 80)->nullable(true);
            $table->string('location_street', 80)->nullable(true);
            $table->string('location_zip', 10)->nullable(true);
            $table->string('location_country_ident', 10)->nullable(true);
            $table->string('location_city', 80)->nullable(true);
            $table->string('location_contact_person', 80)->nullable(true);
            $table->string('location_phone', 80)->nullable(true);
            $table->string('location_email', 240)->nullable(true);
            $table->string('building', 60)->nullable(true);
            $table->string('floor', 60)->nullable(true);
            $table->string('room', 60)->nullable(true);
            $table->string('opening_hours', 60)->nullable(true);
            $table->date('customer_part_warranty_start_at')->nullable(true);
            $table->date('customer_part_warranty_end_at')->nullable(true);
            $table->date('customer_worktime_warranty_start_at')->nullable(true);
            $table->date('customer_worktime_warranty_end_at')->nullable(true);
            $table->date('manufacturer_part_warranty_start_at')->nullable(true);
            $table->date('manufacturer_part_warranty_end_at')->nullable(true);
            $table->date('manufacturer_worktime_warranty_start_at')->nullable(true);
            $table->date('manufacturer_worktime_warranty_end_at')->nullable(true);
            $table->string('manufacturer_warranty_ident', 80)->nullable(true);
            $table->string('contract_ident', 30)->nullable(true);
            $table->date('contract_start_at')->nullable(true);
            $table->date('contract_start_end')->nullable(true);
            $table->date('installed_at')->nullable(true);
            $table->date('last_service_at')->nullable(true);
            $table->string('host_name', 120)->nullable(true);
            $table->string('ip_address', 20)->nullable(true);
            $table->string('mac_address', 20)->nullable(true);
            $table->integer('sla_hours')->default(0)->unsigned();
            $table->boolean('is_fleet_device')->nullable(true);
            $table->boolean('is_color_device')->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->string('system_name', 60)->nullable(true);
            $table->string('system_assignment', 60)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_customer_address_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_delivery_address_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_fma_model_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_last_system_counter_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','serial_number'], 'idx_1');
            $table->index(['hv_company_id','ext_id'], 'idx_2');
        });
        Schema::create('tecd_system_counter', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->dateTime('counter_at')->nullable(true);
            $table->float('total', 10, 2)->nullable(true);
            $table->float('total_mono', 10, 2)->nullable(true);
            $table->float('total_color', 10, 2)->nullable(true);
            $table->float('total_scan', 10, 2)->nullable(true);
            $table->float('pages_a3_mono', 10, 2)->nullable(true);
            $table->float('pages_a3_color', 10, 2)->nullable(true);
            $table->float('pages_a4_mono', 10, 2)->nullable(true);
            $table->float('pages_a4_color', 10, 2)->nullable(true);
            $table->date('day')->nullable(true);
            $table->float('total_consumption', 10, 2)->nullable(true);
            $table->float('mono_consumption', 10, 2)->nullable(true);
            $table->float('color_consumption', 10, 2)->nullable(true);
            $table->float('scan_consumption', 10, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_system_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('description', 80)->nullable(true);
            $table->string('item_group_ident', 20)->nullable(true);
            $table->string('item_group_name', 80)->nullable(true);
            $table->string('manufacturer_item_ident', 40)->nullable(true);
            $table->decimal('stock', 8, 3)->nullable(true);
            $table->boolean('for_mobile')->nullable(true)->default(0);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
        });
        Schema::create('tecd_ticket_position', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('item_ident', 30)->nullable(true);
            $table->string('item_description', 200)->nullable(true);
            $table->double('planned_qty', 6, 2)->nullable(true);
            $table->double('qty', 6, 2)->nullable(true);
            $table->double('reorder_qty', 6, 2)->nullable(true);
            $table->boolean('is_chargeable')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_item_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_ticket_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_ticket', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('parent_ticket_id')->default(0)->unsigned();
            $table->bigInteger('last_ticket_id')->default(0)->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('errorcode', 20)->nullable(true);
            $table->string('service_provider_ticket_ident', 60)->nullable(true);
            $table->timestamp('order_date')->nullable(true);
            $table->timestamp('sla_calc_end_at')->nullable(true);
            $table->timestamp('sla_end_at')->nullable(true);
            $table->longText('ticket_notes')->nullable(true);
            $table->string('customer_ident', 20)->nullable(true);
            $table->string('customer_name_1', 80)->nullable(true);
            $table->string('customer_name_2', 80)->nullable(true);
            $table->string('customer_street', 80)->nullable(true);
            $table->string('customer_zip', 10)->nullable(true);
            $table->string('customer_city', 80)->nullable(true);
            $table->string('customer_country_ident', 10)->nullable(true);
            $table->string('customer_contact_person', 80)->nullable(true);
            $table->string('customer_phone', 80)->nullable(true);
            $table->string('customer_email', 250)->nullable(true);
            $table->string('customer_ticket_ident', 60)->nullable(true);
            $table->string('destination_name_1', 80)->nullable(true);
            $table->string('destination_name_2', 80)->nullable(true);
            $table->string('destination_street', 80)->nullable(true);
            $table->string('destination_zip', 10)->nullable(true);
            $table->string('destination_city', 80)->nullable(true);
            $table->string('destination_country_ident', 10)->nullable(true);
            $table->string('destination_contact_person', 80)->nullable(true);
            $table->string('destination_phone', 80)->nullable(true);
            $table->string('destination_email', 240)->nullable(true);
            $table->string('destination_department', 30)->nullable(true);
            $table->float('destination_lat', 12, 7)->nullable(true);
            $table->float('destination_lon', 12, 7)->nullable(true);
            $table->integer('sla_hours')->default(0)->unsigned();
            $table->date('customer_worktime_warranty_end_at')->nullable(true);
            $table->date('customer_part_warranty_end_at')->nullable(true);
            $table->date('manufacturer_worktime_warranty_end_at')->nullable(true);
            $table->date('manufacturer_part_warranty_end_at')->nullable(true);
            $table->string('manufacturer_warranty_ident', 80)->nullable(true);
            $table->longText('technician_info')->nullable(true);
            $table->longText('internal_comment')->nullable(true);
            $table->string('ticket_email', 240)->nullable(true);
            $table->string('serial_number', 80)->nullable(true);
            $table->string('model_ident', 80)->nullable(true);
            $table->string('item_ident', 30)->nullable(true);
            $table->string('vendor_item_ident', 30)->nullable(true);
            $table->string('location_info', 250)->nullable(true);
            $table->timestamp('planned_start_at')->nullable(true);
            $table->timestamp('planned_end_at')->nullable(true);
            $table->timestamp('transmitted_at')->nullable(true);
            $table->timestamp('readed_at')->nullable(true);
            $table->timestamp('assigned_at')->nullable(true);
            $table->timestamp('drive_at')->nullable(true);
            $table->timestamp('cancel_at')->nullable(true);
            $table->timestamp('work_at')->nullable(true);
            $table->timestamp('finish_at')->nullable(true);
            $table->timestamp('interrupt_at')->nullable(true);
            $table->longText('working_report')->nullable(true);
            $table->timestamp('status_type_at')->nullable(true);
            $table->string('signer', 60)->nullable(true);
            $table->string('signaturefile', 120)->nullable(true);
            $table->integer('milage')->default(0)->unsigned();
            $table->integer('t_value')->default(0)->unsigned();
            $table->integer('k_value')->default(0)->unsigned();
            $table->integer('c_value')->default(0)->unsigned();
            $table->integer('s_value')->default(0)->unsigned();
            $table->boolean('is_released')->nullable(true)->default(0);
            $table->boolean('is_booked')->nullable(true)->default(0);
            $table->boolean('is_new')->nullable(true)->default(0);
            $table->boolean('is_mailed_to_sp')->nullable(true)->default(0);
            $table->string('sp_email', 120)->nullable(true);
            $table->integer('working_units')->default(0);
            $table->boolean('overall_approach')->nullable(true);
            $table->boolean('spare_parts_ordered')->nullable(true);
            $table->string('supplier_ticket_ident', 80)->nullable(true);
            $table->boolean('supplier_ticket_closed')->nullable(true)->default(0);
            $table->boolean('revisit_ticket_created')->nullable(true)->default(0);
            $table->boolean('is_customer_fault')->nullable(true)->default(0);
            $table->boolean('is_service_provider_fault')->nullable(true)->default(0);
            $table->boolean('is_chargeable')->nullable(true)->default(0);
            $table->boolean('is_reversal')->nullable(true)->default(0);
            $table->integer('resubmission_duration')->default(0)->unsigned();
            $table->boolean('external_finished')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_customer_address_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_delivery_address_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_system_id')->nullable(true)->unsigned();
            $table->bigInteger('pcts_revisit_type_id')->nullable(true)->unsigned();
            $table->bigInteger('pcts_order_type_id')->nullable(true)->unsigned();
            $table->bigInteger('pcts_order_status_type_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_change_type_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_external_change_type_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_system_counter_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident','serial_number','customer_ident','model_ident','service_provider_ticket_ident','customer_ticket_ident'], 'idx_1');
        });
        Schema::create('tecd_ticket_ident', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_ticket_note', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('notes')->nullable(true);
            $table->boolean('is_todo')->nullable(true)->default(0);
            $table->bigInteger('delegated_to')->nullable(true)->unsigned();
            $table->boolean('is_finished')->nullable(true)->default(0);
            $table->boolean('is_portal_visible')->nullable(true)->default(0);
            $table->timestamp('finished_at')->nullable(true);
            $table->bigInteger('finished_by')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_ticket_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_ticket_note_type_id')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
        });
        Schema::create('tecd_ticket_note_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->boolean('is_todo')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_ticket_history', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('attribute', 120)->nullable(true);
            $table->longText('old_value')->nullable(true);
            $table->longText('new_value')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_ticket_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_ticket_binary', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('filename', 240)->nullable(true);
            $table->string('filename_org', 240)->nullable(true);
            $table->boolean('send_to_sp')->nullable(true)->default(0);
            $table->boolean('is_service_voucher')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_ticket_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_system_supply_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('serial_number', 80)->nullable(true);
            $table->string('item_ident', 30)->nullable(true);
            $table->string('description', 180)->nullable(true);
            $table->string('accociated_item_ident', 30)->nullable(true);
            $table->string('manufacturer_item_ident', 30)->nullable(true);
            $table->string('type', 20)->nullable(true);
            $table->integer('range')->nullable(true)->default(0);
            $table->boolean('is_standard')->nullable(true)->default(0)->unsigned();
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_system_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','serial_number','item_ident'], 'idx_1');
        });
        Schema::create('tecd_supply_order', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('order_ident', 30)->nullable(true);
            $table->date('order_date')->nullable(true);
            $table->bigInteger('line_no')->nullable(true)->unsigned();
            $table->date('expected_receipt_date')->nullable(true);
            $table->string('serial_number', 80)->nullable(true);
            $table->string('supply_ident', 30)->nullable(true);
            $table->string('supply_type', 30)->nullable(true);
            $table->string('description', 180)->nullable(true);
            $table->string('manufacturer_item_ident', 40)->nullable(true);
            $table->float('qty', 8, 2)->nullable(true)->default(0);
            $table->string('tracking_link', 250)->nullable(true);
            $table->boolean('is_ordered')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('alert_id')->unsigned();
            $table->string('alert_supply_type', 30)->nullable(true);
            $table->string('alert_supply_name', 60)->nullable(true);
            $table->string('alert_colorant', 30)->nullable(true);
            $table->string('alert_message', 240)->nullable(true);
            $table->bigInteger('tecd_system_id')->unsigned();
            $table->integer('tecd_supply_order_status_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->boolean('is_fleet_order')->nullable(true)->default(0);
            $table->boolean('is_skip_order')->nullable(true)->default(0);
            $table->index(['hv_company_id','serial_number'], 'idx_1');
        });
        Schema::create('tecd_info_text', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
        });
        Schema::create('tecd_customer_info_text', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_customer_address_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_info_text_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tecd_model_info_text', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('model_ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tecd_model_id')->nullable(true)->unsigned();
            $table->bigInteger('tecd_info_text_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','model_ident'], 'idx_1');
            $table->index(['model_ident'], 'idx_2');
        });
        Schema::create('tecd_model', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident_1', 60)->nullable(true);
            $table->string('ident_2', 60)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident_1'], 'idx_1');
        });
        Schema::create('tecd_fma_model', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('total_counter_name', 60)->nullable(true);
            $table->string('mono_counter_name', 60)->nullable(true);
            $table->string('color_counter_name', 60)->nullable(true);
            $table->string('scan_counter_name', 60)->nullable(true);
            $table->string('counter_defs', 2048)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->unsigned();
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::table('tecd_delivery_address', function (Blueprint $table) {
            $table->foreign('tecd_customer_address_id')->references('id')->on('tecd_customer_address');
        });
        Schema::table('tecd_system', function (Blueprint $table) {
            $table->foreign('tecd_customer_address_id')->references('id')->on('tecd_customer_address');
        });
        Schema::table('tecd_system', function (Blueprint $table) {
            $table->foreign('tecd_delivery_address_id')->references('id')->on('tecd_delivery_address');
        });
        Schema::table('tecd_system', function (Blueprint $table) {
            $table->foreign('tecd_last_system_counter_id')->references('id')->on('tecd_system_counter');
        });
        Schema::table('tecd_system', function (Blueprint $table) {
            $table->foreign('tecd_fma_model_id')->references('id')->on('tecd_fma_model');
        });
        Schema::table('tecd_system_counter', function (Blueprint $table) {
            $table->foreign('tecd_system_id')->references('id')->on('tecd_system');
        });
        Schema::table('tecd_ticket_position', function (Blueprint $table) {
            $table->foreign('tecd_item_id')->references('id')->on('tecd_item');
        });
        Schema::table('tecd_ticket_position', function (Blueprint $table) {
            $table->foreign('tecd_ticket_id')->references('id')->on('tecd_ticket');
        });
        Schema::table('tecd_ticket', function (Blueprint $table) {
            $table->foreign('tecd_customer_address_id')->references('id')->on('tecd_customer_address');
        });
        Schema::table('tecd_ticket', function (Blueprint $table) {
            $table->foreign('tecd_delivery_address_id')->references('id')->on('tecd_delivery_address');
        });
        Schema::table('tecd_ticket', function (Blueprint $table) {
            $table->foreign('tecd_system_id')->references('id')->on('tecd_system');
        });
        Schema::table('tecd_ticket', function (Blueprint $table) {
            $table->foreign('tecd_system_counter_id')->references('id')->on('tecd_system_counter');
        });
        Schema::table('tecd_ticket_note', function (Blueprint $table) {
            $table->foreign('tecd_ticket_id')->references('id')->on('tecd_ticket');
        });
        Schema::table('tecd_ticket_note', function (Blueprint $table) {
            $table->foreign('tecd_ticket_note_type_id')->references('id')->on('tecd_ticket_note_type');
        });
        Schema::table('tecd_ticket_history', function (Blueprint $table) {
            $table->foreign('tecd_ticket_id')->references('id')->on('tecd_ticket');
        });
        Schema::table('tecd_ticket_binary', function (Blueprint $table) {
            $table->foreign('tecd_ticket_id')->references('id')->on('tecd_ticket');
        });
        Schema::table('tecd_customer_info_text', function (Blueprint $table) {
            $table->foreign('tecd_info_text_id')->references('id')->on('tecd_info_text');
        });
        Schema::table('tecd_customer_info_text', function (Blueprint $table) {
            $table->foreign('tecd_customer_address_id')->references('id')->on('tecd_customer_address');
        });
        Schema::table('tecd_model_info_text', function (Blueprint $table) {
            $table->foreign('tecd_info_text_id')->references('id')->on('tecd_info_text');
        });
        Schema::table('tecd_model_info_text', function (Blueprint $table) {
            $table->foreign('tecd_model_id')->references('id')->on('tecd_model');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('tecd_model_info_text')) {
            Schema::table('tecd_model_info_text', function (Blueprint $table) {
                $table->dropForeign(['tecd_model_id']);
            });
        }
        if (Schema::hasTable('tecd_model_info_text')) {
            Schema::table('tecd_model_info_text', function (Blueprint $table) {
                $table->dropForeign(['tecd_info_text_id']);
            });
        }
        if (Schema::hasTable('tecd_customer_info_text')) {
            Schema::table('tecd_customer_info_text', function (Blueprint $table) {
                $table->dropForeign(['tecd_customer_address_id']);
            });
        }
        if (Schema::hasTable('tecd_customer_info_text')) {
            Schema::table('tecd_customer_info_text', function (Blueprint $table) {
                $table->dropForeign(['tecd_info_text_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_binary')) {
            Schema::table('tecd_ticket_binary', function (Blueprint $table) {
                $table->dropForeign(['tecd_ticket_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_history')) {
            Schema::table('tecd_ticket_history', function (Blueprint $table) {
                $table->dropForeign(['tecd_ticket_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_note')) {
            Schema::table('tecd_ticket_note', function (Blueprint $table) {
                $table->dropForeign(['tecd_ticket_note_type_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_note')) {
            Schema::table('tecd_ticket_note', function (Blueprint $table) {
                $table->dropForeign(['tecd_ticket_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket')) {
            Schema::table('tecd_ticket', function (Blueprint $table) {
                $table->dropForeign(['tecd_system_counter_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket')) {
            Schema::table('tecd_ticket', function (Blueprint $table) {
                $table->dropForeign(['tecd_system_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket')) {
            Schema::table('tecd_ticket', function (Blueprint $table) {
                $table->dropForeign(['tecd_delivery_address_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket')) {
            Schema::table('tecd_ticket', function (Blueprint $table) {
                $table->dropForeign(['tecd_customer_address_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_position')) {
            Schema::table('tecd_ticket_position', function (Blueprint $table) {
                $table->dropForeign(['tecd_ticket_id']);
            });
        }
        if (Schema::hasTable('tecd_ticket_position')) {
            Schema::table('tecd_ticket_position', function (Blueprint $table) {
                $table->dropForeign(['tecd_item_id']);
            });
        }
        if (Schema::hasTable('tecd_system_counter')) {
            Schema::table('tecd_system_counter', function (Blueprint $table) {
                $table->dropForeign(['tecd_system_id']);
            });
        }
        if (Schema::hasTable('tecd_system')) {
            Schema::table('tecd_system', function (Blueprint $table) {
                $table->dropForeign(['tecd_fma_model_id']);
            });
        }
        if (Schema::hasTable('tecd_system')) {
            Schema::table('tecd_system', function (Blueprint $table) {
                $table->dropForeign(['tecd_last_system_counter_id']);
            });
        }
        if (Schema::hasTable('tecd_system')) {
            Schema::table('tecd_system', function (Blueprint $table) {
                $table->dropForeign(['tecd_delivery_address_id']);
            });
        }
        if (Schema::hasTable('tecd_system')) {
            Schema::table('tecd_system', function (Blueprint $table) {
                $table->dropForeign(['tecd_customer_address_id']);
            });
        }
        if (Schema::hasTable('tecd_delivery_address')) {
            Schema::table('tecd_delivery_address', function (Blueprint $table) {
                $table->dropForeign(['tecd_customer_address_id']);
            });
        }
        Schema::dropIfExists('tecd_fma_model');
        Schema::dropIfExists('tecd_model');
        Schema::dropIfExists('tecd_model_info_text');
        Schema::dropIfExists('tecd_customer_info_text');
        Schema::dropIfExists('tecd_info_text');
        Schema::dropIfExists('tecd_supply_order');
        Schema::dropIfExists('tecd_system_supply_item');
        Schema::dropIfExists('tecd_ticket_binary');
        Schema::dropIfExists('tecd_ticket_history');
        Schema::dropIfExists('tecd_ticket_note_type');
        Schema::dropIfExists('tecd_ticket_note');
        Schema::dropIfExists('tecd_ticket_ident');
        Schema::dropIfExists('tecd_ticket');
        Schema::dropIfExists('tecd_ticket_position');
        Schema::dropIfExists('tecd_item');
        Schema::dropIfExists('tecd_system_counter');
        Schema::dropIfExists('tecd_system');
        Schema::dropIfExists('tecd_delivery_address');
        Schema::dropIfExists('tecd_customer_address');
    }
}
