<?php
/*
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a49f9fb1-8133-4a22-b2a3-bbb9785d28fa
 * Migration datetime: 2021-05-17 08:15:59.610409
 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01THS2021051708155961 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ths_manufacturer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('old_id', 20)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_device_model', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('search_1', 60)->nullable(true);
            $table->string('search_2', 60)->nullable(true);
            $table->string('search_3', 60)->nullable(true);
            $table->string('search_4', 60)->nullable(true);
            $table->string('old_id', 20)->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_manufacturer_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_device_model_group_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('old_id', 20)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_manufacturer_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_product_type_id')->nullable(true);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->longText('description')->nullable(true);
            $table->longText('additional_information')->nullable(true);
            $table->longText('internal_information')->nullable(true);
            $table->integer('price_status')->nullable(true);
            $table->boolean('for_catalog')->nullable(true);
            $table->string('specials', 180)->nullable(true);
            $table->integer('mileage')->nullable(true);
            $table->timestamp('is_new_until')->nullable(true);
            $table->boolean('label_print_enabled')->nullable(true)->default(0);
            $table->string('label_manufacturer_1', 60)->nullable(true);
            $table->string('label_manufacturer_2', 60)->nullable(true);
            $table->string('label_manufacturer_3', 60)->nullable(true);
            $table->string('label_manufacturer_4', 60)->nullable(true);
            $table->string('label_manufacturer_5', 60)->nullable(true);
            $table->string('label_model_1', 60)->nullable(true);
            $table->string('label_model_2', 60)->nullable(true);
            $table->string('label_model_3', 60)->nullable(true);
            $table->string('label_model_4', 60)->nullable(true);
            $table->string('label_model_5', 60)->nullable(true);
            $table->boolean('is_released')->nullable(true)->default(0);
            $table->boolean('has_equivalent')->nullable(true)->default(0);
            $table->boolean('has_exclusive')->nullable(true)->default(0);
            $table->boolean('jpg0300_available')->nullable(true);
            $table->boolean('jpg0600_available')->nullable(true);
            $table->boolean('jpg1600_available')->nullable(true);
            $table->integer('old_label_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_color_field_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_article_description_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_article_type_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_label_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
            $table->index(['ident'], 'idx_2');
        });
        Schema::create('ths_device_model_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('old_id', 20)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_oem_ident', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('sort_index')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('sort_index')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_color_field', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_article_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_article_description', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_country_bl', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('country_ident', 30)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_alternate', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('customer_ident', 30)->nullable(true);
            $table->string('item_ident', 30)->nullable(true);
            $table->integer('sort_index')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_customer_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_easyshop_file_counter', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('counter')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_product_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('product_sort_index')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_product_group_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_device_model', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_device_model_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_printer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 120)->nullable(true);
            $table->string('driver_name', 120)->nullable(true);
            $table->string('ip_address', 20)->nullable(true);
            $table->string('mac_address', 30)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_label', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 250)->nullable(true);
            $table->string('ias_label_alias', 60)->nullable(true);
            $table->integer('old_label_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_printer_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_basic_config', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('label_logo_file', 255)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_customer_product', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->boolean('not_for_customer')->nullable(true)->default(0);
            $table->boolean('label_print_enabled')->nullable(true)->default(0);
            $table->string('label_manufacturer_1', 60)->nullable(true);
            $table->string('label_model_1', 60)->nullable(true);
            $table->boolean('label_item_disabled_1')->nullable(true)->default(0);
            $table->string('label_manufacturer_2', 60)->nullable(true);
            $table->string('label_model_2', 60)->nullable(true);
            $table->boolean('label_item_disabled_2')->nullable(true)->default(0);
            $table->string('label_manufacturer_3', 60)->nullable(true);
            $table->string('label_model_3', 60)->nullable(true);
            $table->boolean('label_item_disabled_3')->nullable(true)->default(0);
            $table->string('label_manufacturer_4', 60)->nullable(true);
            $table->string('label_model_4', 60)->nullable(true);
            $table->boolean('label_item_disabled_4')->nullable(true)->default(0);
            $table->string('label_manufacturer_5', 60)->nullable(true);
            $table->string('label_model_5', 60)->nullable(true);
            $table->boolean('label_item_disabled_5')->nullable(true)->default(0);
            $table->integer('old_label_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_customer_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_label_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['ths_product_id','ths_customer_id','label_print_enabled'], 'idx_1');
        });
        Schema::create('ths_customer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('voucher_background_file', 255)->nullable(true);
            $table->string('label_logo_file', 255)->nullable(true);
            $table->string('product_text_replacement', 120)->nullable(true);
            $table->string('article_type_replacement', 120)->nullable(true);
            $table->boolean('csv_export')->nullable(true)->default(0);
            $table->longText('csv_export_format')->nullable(true);
            $table->boolean('order_voucher_import')->nullable(true)->default(0);
            $table->bigInteger('order_voucher_import_type_id')->nullable(true);
            $table->boolean('order_voucher_export')->nullable(true)->default(0);
            $table->bigInteger('order_voucher_export_type_id')->nullable(true);
            $table->boolean('delivery_voucher_export')->nullable(true)->default(0);
            $table->bigInteger('delivery_voucher_export_type_id')->nullable(true);
            $table->boolean('invoice_voucher_export')->nullable(true)->default(0);
            $table->bigInteger('invoice_voucher_export_type_id')->nullable(true);
            $table->boolean('print_voucher')->nullable(true)->default(0);
            $table->boolean('is_export_customer')->nullable(true)->default(0);
            $table->boolean('is_it_scope')->nullable(true)->default(0);
            $table->boolean('old_customer_ident_format')->nullable(true)->default(0);
            $table->boolean('check_double_orders')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
            $table->index(['ident'], 'idx_2');
        });
        Schema::create('ths_product_equivalent', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('notes')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_product_equivalent_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_supplier', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('factor', 3, 1)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
            $table->index(['ident'], 'idx_2');
        });
        Schema::create('ths_product_sales_volume', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('sales_last_month', 12, 2)->nullable(true);
            $table->float('sales_last_month2', 12, 2)->nullable(true);
            $table->float('sales_last_6_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_6_month_average2', 12, 2)->nullable(true);
            $table->float('sales_year_before_last_year_average', 12, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','ident'], 'idx_1');
        });
        Schema::create('ths_file_format', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_language', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('sage_ident', 60)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_voucher_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('sage_ident', 30)->nullable(true);
            $table->string('description', 60)->nullable(true);
            $table->string('email_sender', 80)->nullable(true);
            $table->boolean('is_active')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_printer_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_voucher_type_email_template', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->longText('subject')->nullable(true);
            $table->longText('body')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_voucher_type_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_language_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_email_signature_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_salesman', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('sage_ident', 60)->nullable(true);
            $table->string('office_email', 80)->nullable(true);
            $table->string('office_phone', 80)->nullable(true);
            $table->string('office_mobile', 80)->nullable(true);
            $table->boolean('quotation_voucher')->nullable(true)->default(0);
            $table->boolean('order_voucher')->nullable(true)->default(0);
            $table->boolean('delivery_voucher')->nullable(true)->default(0);
            $table->boolean('invoice_voucher')->nullable(true)->default(0);
            $table->boolean('direct_invoice_voucher')->nullable(true)->default(0);
            $table->boolean('collective_invoice_voucher')->nullable(true)->default(0);
            $table->boolean('cancellation_invoice_voucher')->nullable(true)->default(0);
            $table->boolean('credits_invoice_voucher')->nullable(true)->default(0);
            $table->boolean('reminder_voucher')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_finish_part', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('factor', 3, 1)->nullable(true);
            $table->boolean('is_finished')->nullable(true)->default(0);
            $table->boolean('deleted')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_finish_part_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('stock_total', 12, 2)->nullable(true);
            $table->float('stock_ths', 12, 2)->nullable(true);
            $table->float('stock_parsia', 12, 2)->nullable(true);
            $table->float('minimum_stock_level', 12, 2)->nullable(true);
            $table->float('sales_current', 12, 2)->nullable(true);
            $table->float('sales_last_month', 12, 2)->nullable(true);
            $table->float('sales_last_3_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_6_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_year_average', 12, 2)->nullable(true);
            $table->float('sales_year_before_last_year_average', 12, 2)->nullable(true);
            $table->float('requirement_month', 12, 2)->nullable(true);
            $table->float('requirement_factor', 12, 2)->nullable(true);
            $table->float('requirement_calculated', 12, 2)->nullable(true);
            $table->float('requirement_abf', 12, 2)->nullable(true);
            $table->float('requirement_determined', 12, 2)->nullable(true);
            $table->float('requirement_confirmed', 12, 2)->nullable(true);
            $table->float('requirement_confirmed_changed', 12, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_finish_part_item_resources', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('semimanufactured_ident', 60)->nullable(true);
            $table->float('semimanufactured_stock', 12, 2)->nullable(true);
            $table->float('qty', 12, 2)->nullable(true);
            $table->float('qty2', 12, 2)->nullable(true);
            $table->integer('type')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_raw_material', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->boolean('is_finished')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->unsigned();
            $table->boolean('deleted')->nullable(true)->default(0);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_raw_material_resources', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('stock_total', 12, 2)->nullable(true);
            $table->float('requirement_abf', 12, 2)->nullable(true);
            $table->float('requirement_ordered', 12, 2)->nullable(true);
            $table->float('requirement_production', 12, 2)->nullable(true);
            $table->float('requirement_production_ordered', 12, 2)->nullable(true);
            $table->float('semimanufactured', 12, 2)->nullable(true);
            $table->string('supplier_ident', 60)->nullable(true);
            $table->float('qty', 12, 2)->nullable(true);
            $table->integer('type')->nullable(true)->unsigned();
            $table->float('requirement_factor', 12, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_product_customer_exclusive', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('customer_ident', 30)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_product_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_email_signature', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->longText('signature')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_printer_driver', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('driver_name', 120)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_voucher_action', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('action_type_ident', 30)->nullable(true);
            $table->bigInteger('voucher_id')->nullable(true);
            $table->string('voucher_type_ident', 30)->nullable(true);
            $table->string('voucher_ident', 20)->nullable(true);
            $table->string('receiver', 120)->nullable(true);
            $table->string('source_file', 250)->nullable(true);
            $table->string('destination_file', 250)->nullable(true);
            $table->integer('trails')->nullable(true);
            $table->integer('action_done')->nullable(true)->default(0);
            $table->timestamp('action_done_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_error_message_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','action_type_ident','action_done'], 'idx_1');
        });
        Schema::create('ths_op_raw_material_resources_changed', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('ths_parent_id')->unique()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('raw_material_new_factor', 12, 2)->nullable(true);
            $table->float('requirement_confirmed', 12, 2)->nullable(true);
            $table->boolean('requirement_confirmed_changed')->nullable(true)->default(0);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->unique(['ths_parent_id','ident'], 'idx_1');
        });
        Schema::create('ths_text_container', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('content')->nullable(true);
            $table->boolean('is_intern')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_country', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('name', 60)->nullable(true);
            $table->string('iso_3166_2', 10)->nullable(true);
            $table->string('iso_3166_3', 10)->nullable(true);
            $table->index(['iso_3166_2'], 'idx_1');
        });
        Schema::create('ths_product_sales_volume_history', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('month')->nullable(true);
            $table->integer('year')->nullable(true);
            $table->double('sales_volume', 12, 2)->nullable(true);
        });
        Schema::create('ths_op_production', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('factor', 3, 1)->nullable(true);
            $table->boolean('is_finished')->nullable(true)->default(0);
            $table->boolean('deleted')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_production_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('stock_total', 12, 2)->nullable(true);
            $table->float('stock_ths', 12, 2)->nullable(true);
            $table->float('stock_parsia', 12, 2)->nullable(true);
            $table->float('minimum_stock_level', 12, 2)->nullable(true);
            $table->float('sales_current', 12, 2)->nullable(true);
            $table->float('sales_last_month', 12, 2)->nullable(true);
            $table->float('sales_last_3_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_6_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_year_average', 12, 2)->nullable(true);
            $table->float('sales_year_before_last_year_average', 12, 2)->nullable(true);
            $table->float('requirement_month', 12, 2)->nullable(true);
            $table->float('requirement_factor', 12, 2)->nullable(true);
            $table->float('requirement_calculated', 12, 2)->nullable(true);
            $table->float('requirement_abf', 12, 2)->nullable(true);
            $table->float('requirement_production', 12, 2)->nullable(true);
            $table->float('requirement_production_ordered', 12, 2)->nullable(true);
            $table->float('requirement_determined', 12, 2)->nullable(true);
            $table->float('requirement_confirmed', 12, 2)->nullable(true);
            $table->float('requirement_confirmed_changed', 12, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_trading_goods', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('factor', 3, 1)->nullable(true);
            $table->boolean('create_inquiry')->nullable(true)->default(0);
            $table->boolean('is_finished')->nullable(true)->default(0);
            $table->boolean('deleted')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_trading_goods_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->float('stock_total', 12, 2)->nullable(true);
            $table->float('stock_ths', 12, 2)->nullable(true);
            $table->float('stock_parsia', 12, 2)->nullable(true);
            $table->float('minimum_stock_level', 12, 2)->nullable(true);
            $table->float('sales_current', 12, 2)->nullable(true);
            $table->float('sales_last_month', 12, 2)->nullable(true);
            $table->float('sales_last_3_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_6_month_average', 12, 2)->nullable(true);
            $table->float('sales_last_year_average', 12, 2)->nullable(true);
            $table->float('sales_year_before_last_year_average', 12, 2)->nullable(true);
            $table->float('requirement_month', 12, 2)->nullable(true);
            $table->float('requirement_factor', 12, 2)->nullable(true);
            $table->float('requirement_calculated', 12, 2)->nullable(true);
            $table->float('requirement_abf', 12, 2)->nullable(true);
            $table->float('requirement_ordered', 12, 2)->nullable(true);
            $table->float('requirement_production', 12, 2)->nullable(true);
            $table->float('requirement_production_ordered', 12, 2)->nullable(true);
            $table->float('requirement_determined', 12, 2)->nullable(true);
            $table->float('requirement_confirmed', 12, 2)->nullable(true);
            $table->float('requirement_confirmed_changed', 12, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_trading_goods_supplier_assign', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('assign_ident', 60)->nullable(true);
            $table->boolean('is_fixed_supplier')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('s100_contactperson_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_finish_part_item_info', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('requirement_abf')->nullable(true);
            $table->longText('requirement_ordered')->nullable(true);
            $table->longText('requirement_production')->nullable(true);
            $table->longText('requirement_production_ordered')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_op_finish_part_item_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_production_item_info', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('requirement_abf')->nullable(true);
            $table->longText('requirement_ordered')->nullable(true);
            $table->longText('requirement_production')->nullable(true);
            $table->longText('requirement_production_ordered')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_op_production_item_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_raw_material_resources_info', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ths_op_raw_material_resources_ident', 60)->nullable(true);
            $table->longText('requirement_abf')->nullable(true);
            $table->longText('requirement_ordered')->nullable(true);
            $table->longText('requirement_production')->nullable(true);
            $table->longText('requirement_production_ordered')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_parent_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('ths_op_trading_goods_item_info', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->longText('requirement_abf')->nullable(true);
            $table->longText('requirement_ordered')->nullable(true);
            $table->longText('requirement_production')->nullable(true);
            $table->longText('requirement_production_ordered')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->bigInteger('ths_op_trading_goods_item_id')->nullable(true)->unsigned();
        });
        Schema::create('ths_last_pricelist_price', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('item_ident', 60)->nullable(true);
            $table->float('price', 12, 2)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_pricelist_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','item_ident','ths_pricelist_id'], 'idx_1');
        });
        Schema::create('ths_last_customer_price', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('customer_ident', 60)->nullable(true);
            $table->string('item_ident', 60)->nullable(true);
            $table->float('price', 12, 2)->nullable(true);
            $table->tinyInteger('sync_flag')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id','customer_ident','item_ident'], 'idx_1');
        });
        Schema::create('ths_customer_email_history', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('voucher_type_ident', 30)->nullable(true);
            $table->string('voucher_ident', 20)->nullable(true);
            $table->string('subject', 120)->nullable(true);
            $table->string('receivers', 120)->nullable(true);
            $table->string('attached_file_name', 100)->nullable(true);
            $table->timestamp('sent_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_customer_id')->nullable(true)->unsigned();
            $table->bigInteger('bel_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->index(['hv_company_id','voucher_type_ident'], 'idx_1');
            $table->index(['hv_company_id','subject'], 'idx_2');
            $table->index(['hv_company_id','receivers'], 'idx_3');
            $table->index(['hv_company_id','voucher_ident'], 'idx_4');
        });
        Schema::create('ths_customer_file_history', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('voucher_ident', 20)->nullable(true);
            $table->string('customer_voucher_ident', 60)->nullable(true);
            $table->string('filename', 120)->nullable(true);
            $table->boolean('success')->nullable(true)->default(0);
            $table->boolean('is_export')->nullable(true)->default(0);
            $table->timestamp('processed_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('ths_customer_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_file_format_id')->nullable(true)->unsigned();
            $table->bigInteger('ths_error_message_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->index(['hv_company_id','voucher_ident','is_export'], 'idx_1');
            $table->index(['hv_company_id','customer_voucher_ident','is_export'], 'idx_2');
        });
        Schema::table('ths_device_model', function (Blueprint $table) {
            $table->foreign('ths_manufacturer_id')->references('id')->on('ths_manufacturer');
        });
        Schema::table('ths_device_model', function (Blueprint $table) {
            $table->foreign('ths_device_model_group_id')->references('id')->on('ths_device_model_group');
        });
        Schema::table('ths_product_group', function (Blueprint $table) {
            $table->foreign('ths_manufacturer_id')->references('id')->on('ths_manufacturer');
        });
        Schema::table('ths_product', function (Blueprint $table) {
            $table->foreign('ths_color_field_id')->references('id')->on('ths_color_field');
        });
        Schema::table('ths_product', function (Blueprint $table) {
            $table->foreign('ths_article_description_id')->references('id')->on('ths_article_description');
        });
        Schema::table('ths_product', function (Blueprint $table) {
            $table->foreign('ths_article_type_id')->references('id')->on('ths_article_type');
        });
        Schema::table('ths_product', function (Blueprint $table) {
            $table->foreign('ths_label_id')->references('id')->on('ths_label');
        });
        Schema::table('ths_product_oem_ident', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_type', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_country_bl', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_alternate', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_alternate', function (Blueprint $table) {
            $table->foreign('ths_customer_id')->references('id')->on('ths_customer');
        });
        Schema::table('ths_product_product_group', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_product_group', function (Blueprint $table) {
            $table->foreign('ths_product_group_id')->references('id')->on('ths_product_group');
        });
        Schema::table('ths_product_device_model', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_device_model', function (Blueprint $table) {
            $table->foreign('ths_device_model_id')->references('id')->on('ths_device_model');
        });
        Schema::table('ths_label', function (Blueprint $table) {
            $table->foreign('ths_printer_id')->references('id')->on('ths_printer');
        });
        Schema::table('ths_customer_product', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_customer_product', function (Blueprint $table) {
            $table->foreign('ths_label_id')->references('id')->on('ths_label');
        });
        Schema::table('ths_customer_product', function (Blueprint $table) {
            $table->foreign('ths_customer_id')->references('id')->on('ths_customer');
        });
        Schema::table('ths_product_equivalent', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_product_equivalent', function (Blueprint $table) {
            $table->foreign('ths_product_equivalent_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_voucher_type', function (Blueprint $table) {
            $table->foreign('ths_printer_id')->references('id')->on('ths_printer');
        });
        Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
            $table->foreign('ths_voucher_type_id')->references('id')->on('ths_voucher_type');
        });
        Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
            $table->foreign('ths_language_id')->references('id')->on('ths_language');
        });
        Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
            $table->foreign('ths_email_signature_id')->references('id')->on('ths_email_signature');
        });
        Schema::table('ths_op_finish_part_item', function (Blueprint $table) {
            $table->foreign('ths_parent_id')->references('id')->on('ths_op_finish_part');
        });
        Schema::table('ths_op_finish_part_item_resources', function (Blueprint $table) {
            $table->foreign('ths_parent_id')->references('id')->on('ths_op_finish_part_item');
        });
        Schema::table('ths_product_customer_exclusive', function (Blueprint $table) {
            $table->foreign('ths_product_id')->references('id')->on('ths_product');
        });
        Schema::table('ths_voucher_action', function (Blueprint $table) {
            $table->foreign('ths_error_message_id')->references('id')->on('ths_text_container');
        });
        Schema::table('ths_op_production_item', function (Blueprint $table) {
            $table->foreign('ths_parent_id')->references('id')->on('ths_op_production');
        });
        Schema::table('ths_op_trading_goods_item', function (Blueprint $table) {
            $table->foreign('ths_parent_id')->references('id')->on('ths_op_trading_goods');
        });
        Schema::table('ths_op_finish_part_item_info', function (Blueprint $table) {
            $table->foreign('ths_op_finish_part_item_id')->references('id')->on('ths_op_finish_part_item');
        });
        Schema::table('ths_op_production_item_info', function (Blueprint $table) {
            $table->foreign('ths_op_production_item_id')->references('id')->on('ths_op_production_item');
        });
        Schema::table('ths_op_trading_goods_item_info', function (Blueprint $table) {
//            $table->foreign('ths_op_trading_goods_item_id')->references('id')->on('ths_op_trading_goods_item');
        });
        Schema::table('ths_customer_email_history', function (Blueprint $table) {
            $table->foreign('ths_customer_id')->references('id')->on('ths_customer');
        });
        Schema::table('ths_customer_file_history', function (Blueprint $table) {
            $table->foreign('ths_customer_id')->references('id')->on('ths_customer');
        });
        Schema::table('ths_customer_file_history', function (Blueprint $table) {
            $table->foreign('ths_file_format_id')->references('id')->on('ths_file_format');
        });
        Schema::table('ths_customer_file_history', function (Blueprint $table) {
            $table->foreign('ths_error_message_id')->references('id')->on('ths_text_container');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('ths_customer_file_history')) {
            Schema::table('ths_customer_file_history', function (Blueprint $table) {
                $table->dropForeign(['ths_error_message_id']);
            });
        }
        if (Schema::hasTable('ths_customer_file_history')) {
            Schema::table('ths_customer_file_history', function (Blueprint $table) {
                $table->dropForeign(['ths_file_format_id']);
            });
        }
        if (Schema::hasTable('ths_customer_file_history')) {
            Schema::table('ths_customer_file_history', function (Blueprint $table) {
                $table->dropForeign(['ths_customer_id']);
            });
        }
        if (Schema::hasTable('ths_customer_email_history')) {
            Schema::table('ths_customer_email_history', function (Blueprint $table) {
                $table->dropForeign(['ths_customer_id']);
            });
        }
        if (Schema::hasTable('ths_op_trading_goods_item_info')) {
            Schema::table('ths_op_trading_goods_item_info', function (Blueprint $table) {
                $table->dropForeign(['ths_op_trading_goods_item_id']);
            });
        }
        if (Schema::hasTable('ths_op_production_item_info')) {
            Schema::table('ths_op_production_item_info', function (Blueprint $table) {
                $table->dropForeign(['ths_op_production_item_id']);
            });
        }
        if (Schema::hasTable('ths_op_finish_part_item_info')) {
            Schema::table('ths_op_finish_part_item_info', function (Blueprint $table) {
                $table->dropForeign(['ths_op_finish_part_item_id']);
            });
        }
        if (Schema::hasTable('ths_op_trading_goods_item')) {
            Schema::table('ths_op_trading_goods_item', function (Blueprint $table) {
                $table->dropForeign(['ths_parent_id']);
            });
        }
        if (Schema::hasTable('ths_op_production_item')) {
            Schema::table('ths_op_production_item', function (Blueprint $table) {
                $table->dropForeign(['ths_parent_id']);
            });
        }
        if (Schema::hasTable('ths_voucher_action')) {
            Schema::table('ths_voucher_action', function (Blueprint $table) {
                $table->dropForeign(['ths_error_message_id']);
            });
        }
        if (Schema::hasTable('ths_product_customer_exclusive')) {
            Schema::table('ths_product_customer_exclusive', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_op_finish_part_item_resources')) {
            Schema::table('ths_op_finish_part_item_resources', function (Blueprint $table) {
                $table->dropForeign(['ths_parent_id']);
            });
        }
        if (Schema::hasTable('ths_op_finish_part_item')) {
            Schema::table('ths_op_finish_part_item', function (Blueprint $table) {
                $table->dropForeign(['ths_parent_id']);
            });
        }
        if (Schema::hasTable('ths_voucher_type_email_template')) {
            Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
                $table->dropForeign(['ths_email_signature_id']);
            });
        }
        if (Schema::hasTable('ths_voucher_type_email_template')) {
            Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
                $table->dropForeign(['ths_language_id']);
            });
        }
        if (Schema::hasTable('ths_voucher_type_email_template')) {
            Schema::table('ths_voucher_type_email_template', function (Blueprint $table) {
                $table->dropForeign(['ths_voucher_type_id']);
            });
        }
        if (Schema::hasTable('ths_voucher_type')) {
            Schema::table('ths_voucher_type', function (Blueprint $table) {
                $table->dropForeign(['ths_printer_id']);
            });
        }
        if (Schema::hasTable('ths_product_equivalent')) {
            Schema::table('ths_product_equivalent', function (Blueprint $table) {
                $table->dropForeign(['ths_product_equivalent_id']);
            });
        }
        if (Schema::hasTable('ths_product_equivalent')) {
            Schema::table('ths_product_equivalent', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_customer_product')) {
            Schema::table('ths_customer_product', function (Blueprint $table) {
                $table->dropForeign(['ths_customer_id']);
            });
        }
        if (Schema::hasTable('ths_customer_product')) {
            Schema::table('ths_customer_product', function (Blueprint $table) {
                $table->dropForeign(['ths_label_id']);
            });
        }
        if (Schema::hasTable('ths_customer_product')) {
            Schema::table('ths_customer_product', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_label')) {
            Schema::table('ths_label', function (Blueprint $table) {
                $table->dropForeign(['ths_printer_id']);
            });
        }
        if (Schema::hasTable('ths_product_device_model')) {
            Schema::table('ths_product_device_model', function (Blueprint $table) {
                $table->dropForeign(['ths_device_model_id']);
            });
        }
        if (Schema::hasTable('ths_product_device_model')) {
            Schema::table('ths_product_device_model', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product_product_group')) {
            Schema::table('ths_product_product_group', function (Blueprint $table) {
                $table->dropForeign(['ths_product_group_id']);
            });
        }
        if (Schema::hasTable('ths_product_product_group')) {
            Schema::table('ths_product_product_group', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product_alternate')) {
            Schema::table('ths_product_alternate', function (Blueprint $table) {
                $table->dropForeign(['ths_customer_id']);
            });
        }
        if (Schema::hasTable('ths_product_alternate')) {
            Schema::table('ths_product_alternate', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product_country_bl')) {
            Schema::table('ths_product_country_bl', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product_type')) {
            Schema::table('ths_product_type', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product_oem_ident')) {
            Schema::table('ths_product_oem_ident', function (Blueprint $table) {
                $table->dropForeign(['ths_product_id']);
            });
        }
        if (Schema::hasTable('ths_product')) {
            Schema::table('ths_product', function (Blueprint $table) {
                $table->dropForeign(['ths_label_id']);
            });
        }
        if (Schema::hasTable('ths_product')) {
            Schema::table('ths_product', function (Blueprint $table) {
                $table->dropForeign(['ths_article_type_id']);
            });
        }
        if (Schema::hasTable('ths_product')) {
            Schema::table('ths_product', function (Blueprint $table) {
                $table->dropForeign(['ths_article_description_id']);
            });
        }
        if (Schema::hasTable('ths_product')) {
            Schema::table('ths_product', function (Blueprint $table) {
                $table->dropForeign(['ths_color_field_id']);
            });
        }
        if (Schema::hasTable('ths_product_group')) {
            Schema::table('ths_product_group', function (Blueprint $table) {
                $table->dropForeign(['ths_manufacturer_id']);
            });
        }
        if (Schema::hasTable('ths_device_model')) {
            Schema::table('ths_device_model', function (Blueprint $table) {
                $table->dropForeign(['ths_device_model_group_id']);
            });
        }
        if (Schema::hasTable('ths_device_model')) {
            Schema::table('ths_device_model', function (Blueprint $table) {
                $table->dropForeign(['ths_manufacturer_id']);
            });
        }
        Schema::dropIfExists('ths_customer_file_history');
        Schema::dropIfExists('ths_customer_email_history');
        Schema::dropIfExists('ths_last_customer_price');
        Schema::dropIfExists('ths_last_pricelist_price');
        Schema::dropIfExists('ths_op_trading_goods_item_info');
        Schema::dropIfExists('ths_op_raw_material_resources_info');
        Schema::dropIfExists('ths_op_production_item_info');
        Schema::dropIfExists('ths_op_finish_part_item_info');
        Schema::dropIfExists('ths_op_trading_goods_supplier_assign');
        Schema::dropIfExists('ths_op_trading_goods_item');
        Schema::dropIfExists('ths_op_trading_goods');
        Schema::dropIfExists('ths_op_production_item');
        Schema::dropIfExists('ths_op_production');
        Schema::dropIfExists('ths_product_sales_volume_history');
        Schema::dropIfExists('ths_country');
        Schema::dropIfExists('ths_text_container');
        Schema::dropIfExists('ths_op_raw_material_resources_changed');
        Schema::dropIfExists('ths_voucher_action');
        Schema::dropIfExists('ths_printer_driver');
        Schema::dropIfExists('ths_email_signature');
        Schema::dropIfExists('ths_product_customer_exclusive');
        Schema::dropIfExists('ths_op_raw_material_resources');
        Schema::dropIfExists('ths_op_raw_material');
        Schema::dropIfExists('ths_op_finish_part_item_resources');
        Schema::dropIfExists('ths_op_finish_part_item');
        Schema::dropIfExists('ths_op_finish_part');
        Schema::dropIfExists('ths_salesman');
        Schema::dropIfExists('ths_voucher_type_email_template');
        Schema::dropIfExists('ths_voucher_type');
        Schema::dropIfExists('ths_language');
        Schema::dropIfExists('ths_file_format');
        Schema::dropIfExists('ths_product_sales_volume');
        Schema::dropIfExists('ths_supplier');
        Schema::dropIfExists('ths_product_equivalent');
        Schema::dropIfExists('ths_customer');
        Schema::dropIfExists('ths_customer_product');
        Schema::dropIfExists('ths_basic_config');
        Schema::dropIfExists('ths_label');
        Schema::dropIfExists('ths_printer');
        Schema::dropIfExists('ths_product_device_model');
        Schema::dropIfExists('ths_product_product_group');
        Schema::dropIfExists('ths_easyshop_file_counter');
        Schema::dropIfExists('ths_product_alternate');
        Schema::dropIfExists('ths_product_country_bl');
        Schema::dropIfExists('ths_article_description');
        Schema::dropIfExists('ths_article_type');
        Schema::dropIfExists('ths_color_field');
        Schema::dropIfExists('ths_product_type');
        Schema::dropIfExists('ths_product_oem_ident');
        Schema::dropIfExists('ths_device_model_group');
        Schema::dropIfExists('ths_product');
        Schema::dropIfExists('ths_product_group');
        Schema::dropIfExists('ths_device_model');
        Schema::dropIfExists('ths_manufacturer');
    }
}
