<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a49f9fb1-8133-4a22-b2a3-bbb9785d28fa
 * Migration datetime: 2021-05-17 08:15:59.610409
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01IABO2021051708155961 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('iabo_user_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->longText('description')->nullable(true);
            $table->string('com_address', 5)->nullable(true);
            $table->bigInteger('iabo_connection_type_id')->nullable(true)->default(2);
            $table->bigInteger('created_by')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('iabo_knowledge', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->string('ext_link', 180)->nullable(true);
            $table->longText('content')->nullable(true);
            $table->smallInteger('content_type_id')->nullable(true)->default(0);
            $table->string('node_ident', 10)->nullable(true);
            $table->string('node_number', 50)->nullable(true);
            $table->string('knowledge_areas', 500)->nullable(true);
            $table->string('color', 15)->nullable(true);
            $table->string('icon_cls', 20)->nullable(true);
            $table->boolean('private')->nullable(true)->default(0);
            $table->string('com_address', 5)->nullable(true);
            $table->bigInteger('iabo_connection_type_id')->nullable(true)->default(4);
            $table->bigInteger('created_by')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('iabo_user', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('loginname', 30)->nullable(true);
            $table->string('knowledge_com_addresses', 1024)->nullable(true);
            $table->bigInteger('iabo_connection_type_id')->nullable(true)->default(1);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('iabo_knowledge_area', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->longText('description')->nullable(true);
            $table->string('com_address', 5)->nullable(true);
            $table->bigInteger('iabo_connection_type_id')->nullable(true)->default(3);
            $table->bigInteger('created_by')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('iabo_knowledge_log', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('access_type', 20)->nullable(true);
            $table->string('com_address', 5)->nullable(true);
            $table->bigInteger('created_by')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
        });
        Schema::create('iabo_connection', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('sort_index')->nullable(true)->default(0);
            $table->bigInteger('iabo_connection_type_id_1')->nullable(true);
            $table->bigInteger('key_1')->nullable(true);
            $table->bigInteger('iabo_connection_type_id_2')->nullable(true);
            $table->bigInteger('key_2')->nullable(true);
            $table->boolean('auto_created')->nullable(true)->default(0);
            $table->string('com_address', 5)->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->unique(['iabo_connection_type_id_1','key_1','iabo_connection_type_id_2','key_2'], 'idx_1');
            $table->unique(['iabo_connection_type_id_2','key_2','iabo_connection_type_id_1','key_1'], 'idx_2');
        });
        Schema::create('iabo_connection_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 20)->nullable(true);
            $table->timestamp('created_at')->nullable(true);
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('iabo_connection_type');
        Schema::dropIfExists('iabo_connection');
        Schema::dropIfExists('iabo_knowledge_log');
        Schema::dropIfExists('iabo_knowledge_area');
        Schema::dropIfExists('iabo_user');
        Schema::dropIfExists('iabo_knowledge');
        Schema::dropIfExists('iabo_user_group');
    }
}
