<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a49f9fb1-8133-4a22-b2a3-bbb9785d28fa
 * Migration datetime: 2021-05-17 08:15:59.610409
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations0100PCTS2021051708155961 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pcts_urgency', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->tinyInteger('priority')->nullable(true)->default(0)->unsigned();
            $table->string('color', 7)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_order_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('workflow_ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->boolean('show_new_delivery_address')->nullable(true)->default(0);
            $table->string('ext_voucher_type', 30)->nullable(true);
            $table->string('ticket_email_subject', 250)->nullable(true);
            $table->longText('ticket_email_body')->nullable(true);
            $table->boolean('creation_portal_warning')->nullable(true)->default(0);
            $table->string('creation_email', 240)->nullable(true);
            $table->boolean('send_customer_ticket_mail')->nullable(true)->default(0);
            $table->boolean('erp_bool_1')->nullable(true);
            $table->boolean('erp_bool_2')->nullable(true);
            $table->boolean('not_selectable')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_text_block', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->text('content')->nullable(true);
            $table->boolean('for_web')->nullable(true)->default(0)->unsigned();
            $table->boolean('for_mobile')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_sla', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->integer('sla_hours')->nullable(true)->default(0);
            $table->boolean('nbd')->nullable(true)->default(0);
            $table->boolean('second_nbd')->nullable(true)->default(0);
            $table->boolean('third_nbd')->nullable(true)->default(0);
            $table->timestamp('timeslot_start_at')->nullable(true);
            $table->timestamp('timeslot_end_at')->nullable(true);
            $table->timestamp('warning_time_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('pcts_urgency_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_symptom', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_reason', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_action', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_resource_status_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->boolean('is_order')->nullable(true)->default(0)->unsigned();
            $table->boolean('is_ticket')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_order_status_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_error_code', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_contact_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_contract_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->string('erp_contract_type_ident', 20)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('pcts_piet', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->string('filename', 180)->nullable(true);
            $table->string('customer_ident', 20)->nullable(true);
            $table->boolean('customer_finished')->nullable(true)->default(0);
            $table->string('contract_ident', 30)->nullable(true);
            $table->string('url', 250)->nullable(true);
            $table->date('url_valid_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('pcts_piet_system', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('row')->nullable(true)->unsigned();
            $table->string('fieldname', 10)->nullable(true);
            $table->string('title', 55)->nullable(true);
            $table->string('str_value', 200)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('pcts_piet_id')->nullable(true)->unsigned();
            $table->bigInteger('pcts_piet_column_cfg_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('pcts_piet_col_cfg', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->boolean('is_current')->nullable(true)->default(0)->unsigned();
            $table->string('xls_name', 80)->nullable(true);
            $table->integer('xls_index')->nullable(true);
            $table->string('sage_name', 80)->nullable(true);
            $table->integer('column_index')->nullable(true);
            $table->string('column_type', 20)->nullable(true);
            $table->string('column_title', 80)->nullable(true);
            $table->string('column_format', 20)->nullable(true);
            $table->string('column_edit_format', 20)->nullable(true);
            $table->string('column_output_format', 20)->nullable(true);
            $table->string('column_align', 10)->nullable(true);
            $table->integer('column_width')->nullable(true);
            $table->string('column_edit_type', 20)->nullable(true);
            $table->string('column_edit_data_access', 120)->nullable(true);
            $table->string('column_default', 120)->nullable(true);
            $table->boolean('import')->nullable(true)->default(0)->unsigned();
            $table->integer('admin_index')->nullable(true);
            $table->boolean('admin_enabled')->nullable(true)->default(0)->unsigned();
            $table->boolean('admin_visible')->nullable(true)->default(0)->unsigned();
            $table->boolean('admin_editable')->nullable(true)->default(0)->unsigned();
            $table->boolean('admin_required')->nullable(true)->default(0)->unsigned();
            $table->integer('management_index')->nullable(true);
            $table->boolean('management_enabled')->nullable(true)->default(0)->unsigned();
            $table->boolean('management_visible')->nullable(true)->default(0)->unsigned();
            $table->boolean('management_editable')->nullable(true)->default(0)->unsigned();
            $table->boolean('management_required')->nullable(true)->default(0)->unsigned();
            $table->integer('customer_index')->nullable(true);
            $table->boolean('customer_enabled')->nullable(true)->default(0)->unsigned();
            $table->boolean('customer_visible')->nullable(true)->default(0)->unsigned();
            $table->boolean('customer_editable')->nullable(true)->default(0)->unsigned();
            $table->boolean('customer_required')->nullable(true)->default(0)->unsigned();
            $table->string('fieldname', 10)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('pcts_piet_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('s100_customer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('Kto', 20)->nullable(true);
            $table->string('Matchcode', 120)->nullable(true);
            $table->string('Name1', 80)->nullable(true);
            $table->string('LieferLand', 20)->nullable(true);
            $table->string('LieferPLZ', 80)->nullable(true);
            $table->string('LieferOrt', 80)->nullable(true);
            $table->string('LieferStrasse', 80)->nullable(true);
            $table->string('Telefon', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('s100_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('Artikelnummer', 20)->nullable(true);
            $table->string('Artikelgruppe', 20)->nullable(true);
            $table->string('Geraetegruppe', 20)->nullable(true);
            $table->string('Matchcode', 120)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('s100_address', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('Adresse')->nullable(true)->unsigned();
            $table->string('Matchcode', 120)->nullable(true);
            $table->string('Name1', 80)->nullable(true);
            $table->string('LieferLand', 20)->nullable(true);
            $table->string('LieferPLZ', 80)->nullable(true);
            $table->string('LieferOrt', 80)->nullable(true);
            $table->string('LieferStrasse', 80)->nullable(true);
            $table->string('Telefon', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('pcts_revisit_reason', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::table('pcts_sla', function (Blueprint $table) {
            $table->foreign('pcts_urgency_id')->references('id')->on('pcts_urgency');
        });
        Schema::table('pcts_piet_system', function (Blueprint $table) {
            $table->foreign('pcts_piet_id')->references('id')->on('pcts_piet');
        });
        Schema::table('pcts_piet_system', function (Blueprint $table) {
            $table->foreign('pcts_piet_column_cfg_id')->references('id')->on('pcts_piet_col_cfg');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('pcts_piet_system')) {
            Schema::table('pcts_piet_system', function (Blueprint $table) {
                $table->dropForeign(['pcts_piet_column_cfg_id']);
            });
        }
        if (Schema::hasTable('pcts_piet_system')) {
            Schema::table('pcts_piet_system', function (Blueprint $table) {
                $table->dropForeign(['pcts_piet_id']);
            });
        }
        if (Schema::hasTable('pcts_sla')) {
            Schema::table('pcts_sla', function (Blueprint $table) {
                $table->dropForeign(['pcts_urgency_id']);
            });
        }
        Schema::dropIfExists('pcts_revisit_reason');
        Schema::dropIfExists('s100_address');
        Schema::dropIfExists('s100_item');
        Schema::dropIfExists('s100_customer');
        Schema::dropIfExists('pcts_piet_col_cfg');
        Schema::dropIfExists('pcts_piet_system');
        Schema::dropIfExists('pcts_piet');
        Schema::dropIfExists('pcts_contract_type');
        Schema::dropIfExists('pcts_contact_type');
        Schema::dropIfExists('pcts_error_code');
        Schema::dropIfExists('pcts_order_status_type');
        Schema::dropIfExists('pcts_resource_status_type');
        Schema::dropIfExists('pcts_action');
        Schema::dropIfExists('pcts_reason');
        Schema::dropIfExists('pcts_symptom');
        Schema::dropIfExists('pcts_sla');
        Schema::dropIfExists('pcts_text_block');
        Schema::dropIfExists('pcts_order_type');
        Schema::dropIfExists('pcts_urgency');
    }
}
