<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a49f9fb1-8133-4a22-b2a3-bbb9785d28fa-01
 * Migration datetime: 2021-05-17 08:15:59.610409
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01PRG2021051708155961 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('prg_ps_question_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_question', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->text('question_text')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_question_group_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_question_answer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('answer_text', 80)->nullable(true);
            $table->integer('answer_points')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_question_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_question_group_result', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->text('result_text')->nullable(true);
            $table->integer('max_points')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_question_group_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_survey', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('salutation', 40)->nullable(true);
            $table->string('firstname', 80)->nullable(true);
            $table->string('lastname', 80)->nullable(true);
            $table->string('phone', 30)->nullable(true);
            $table->string('company', 80)->nullable(true);
            $table->string('email', 120)->nullable(true);
            $table->string('branch', 80)->nullable(true);
            $table->string('work_position', 80)->nullable(true);
            $table->string('department', 80)->nullable(true);
            $table->integer('number_of_employees')->nullable(true)->default(0)->unsigned();
            $table->integer('number_of_office_workplaces')->nullable(true)->default(0)->unsigned();
            $table->longText('memo')->nullable(true);
            $table->string('origin', 15)->nullable(true);
            $table->integer('mail_id')->nullable(true)->unsigned();
            $table->timestamp('mail_at')->nullable(true);
            $table->text('mail_text')->nullable(true);
            $table->text('result_answer')->nullable(true);
            $table->boolean('email_send')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_survey_result', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('points')->nullable(true)->unsigned();
            $table->text('result_text')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_survey_id')->unsigned();
            $table->bigInteger('prg_ps_question_group_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_survey_answer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('answer_text', 80)->nullable(true);
            $table->integer('points')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_survey_id')->unsigned();
            $table->bigInteger('prg_ps_question_id')->unsigned();
            $table->bigInteger('prg_ps_question_answer_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('prg_ps_survey_binary', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->binary('bin_data')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('prg_ps_survey_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::table('prg_ps_question', function (Blueprint $table) {
            $table->foreign('prg_ps_question_group_id')->references('id')->on('prg_ps_question_group');
        });
        Schema::table('prg_ps_question_answer', function (Blueprint $table) {
            $table->foreign('prg_ps_question_id')->references('id')->on('prg_ps_question');
        });
        Schema::table('prg_ps_question_group_result', function (Blueprint $table) {
            $table->foreign('prg_ps_question_group_id')->references('id')->on('prg_ps_question_group');
        });
        Schema::table('prg_ps_survey_result', function (Blueprint $table) {
            $table->foreign('prg_ps_question_group_id')->references('id')->on('prg_ps_question_group');
        });
        Schema::table('prg_ps_survey_result', function (Blueprint $table) {
            $table->foreign('prg_ps_survey_id')->references('id')->on('prg_ps_survey');
        });
        Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
            $table->foreign('prg_ps_question_id')->references('id')->on('prg_ps_question');
        });
        Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
            $table->foreign('prg_ps_question_answer_id')->references('id')->on('prg_ps_question_answer');
        });
        Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
            $table->foreign('prg_ps_survey_id')->references('id')->on('prg_ps_survey');
        });
        Schema::table('prg_ps_survey_binary', function (Blueprint $table) {
            $table->foreign('prg_ps_survey_id')->references('id')->on('prg_ps_survey');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('prg_ps_survey_binary')) {
            Schema::table('prg_ps_survey_binary', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_survey_id']);
            });
        }
        if (Schema::hasTable('prg_ps_survey_answer')) {
            Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_survey_id']);
            });
        }
        if (Schema::hasTable('prg_ps_survey_answer')) {
            Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_answer_id']);
            });
        }
        if (Schema::hasTable('prg_ps_survey_answer')) {
            Schema::table('prg_ps_survey_answer', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_id']);
            });
        }
        if (Schema::hasTable('prg_ps_survey_result')) {
            Schema::table('prg_ps_survey_result', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_survey_id']);
            });
        }
        if (Schema::hasTable('prg_ps_survey_result')) {
            Schema::table('prg_ps_survey_result', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_group_id']);
            });
        }
        if (Schema::hasTable('prg_ps_question_group_result')) {
            Schema::table('prg_ps_question_group_result', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_group_id']);
            });
        }
        if (Schema::hasTable('prg_ps_question_answer')) {
            Schema::table('prg_ps_question_answer', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_id']);
            });
        }
        if (Schema::hasTable('prg_ps_question')) {
            Schema::table('prg_ps_question', function (Blueprint $table) {
                $table->dropForeign(['prg_ps_question_group_id']);
            });
        }
        Schema::dropIfExists('prg_ps_survey_binary');
        Schema::dropIfExists('prg_ps_survey_answer');
        Schema::dropIfExists('prg_ps_survey_result');
        Schema::dropIfExists('prg_ps_survey');
        Schema::dropIfExists('prg_ps_question_group_result');
        Schema::dropIfExists('prg_ps_question_answer');
        Schema::dropIfExists('prg_ps_question');
        Schema::dropIfExists('prg_ps_question_group');
    }
}
