<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVCompany
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $name_1
* @property string $name_2
* @property string $street
* @property string $zip
* @property string $city
* @property string $contact_person
* @property string $contact_office_phone
* @property string $contact_office_mobile
* @property string $contact_office_email
* @property string $web
* @property \Carbon\Carbon $access_until
* @property longText $config
* @property boolean $auto_password_change
* @property boolean $is_master
* @property string $domain_shortcut
* @property string $copyright_label
* @property string $favicon
* @property string $browser_title
* @property string $logo
* @property bigInteger $hv_country_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVCountry|null $hvCountry
* @property \Illuminate\Database\Eloquent\Collection $hvCompanyMenus
* @property \Illuminate\Database\Eloquent\Collection $hvUsers
*/ 
abstract class HVCompany extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_company';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['auto_password_change' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'name_1' => 'string',
        'name_2' => 'string',
        'street' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'contact_person' => 'string',
        'contact_office_phone' => 'string',
        'contact_office_mobile' => 'string',
        'contact_office_email' => 'string',
        'web' => 'string',
        'access_until' => 'datetime',
        'config' => 'string',
        'auto_password_change' => 'boolean',
        'is_master' => 'boolean',
        'domain_shortcut' => 'string',
        'copyright_label' => 'string',
        'favicon' => 'string',
        'browser_title' => 'string',
        'logo' => 'string',
        'hv_country_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvCountry()
    {
        return $this->belongsTo('\App\Models\hv\HVCountry', 'hv_country_id', 'id');
    }
    
    public function hvCompanyMenus()
    {
        return $this->hasMany('\App\Models\hv\HVCompanyMenu', 'hv_company_id', 'id');
    }
    
    public function hvUsers()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_company_id', 'id');
    }
}
