<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVCountry
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $iso_code_1
* @property string $iso_code_2
* @property string $ident
* @property bigInteger $sort_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvCompanies
* @property \Illuminate\Database\Eloquent\Collection $hvUsers
* @property \Illuminate\Database\Eloquent\Collection $tmBuildings
* @property \Illuminate\Database\Eloquent\Collection $TMServiceProviders
*/ 
abstract class HVCountry extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_country';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['sort_id' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'iso_code_1' => 'string',
        'iso_code_2' => 'string',
        'ident' => 'string',
        'sort_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvCompanies()
    {
        return $this->hasMany('\App\Models\hv\HVCompany', 'hv_country_id', 'id');
    }
    
    public function hvUsers()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_country_id', 'id');
    }
    
    public function tmBuildings()
    {
        return $this->hasMany('\App\Models\tm\TMBuilding', 'hv_country_id', 'id');
    }
    
    public function TMServiceProviders()
    {
        return $this->hasMany('\App\Models\tm\TMServiceProvider', 'hv_country_id', 'id');
    }
}
