<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVCompanyDepartment
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property bigInteger $hv_company_id
* @property string $street
* @property string $zip
* @property string $city
* @property string $country_ident
* @property double $lat
* @property double $lon
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvUsers
*/ 
abstract class HVCompanyDepartment extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_company_department';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'hv_company_id' => 'integer',
        'street' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'country_ident' => 'string',
        'lat' => 'double',
        'lon' => 'double',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvUsers()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_company_department_id', 'id');
    }
}
