<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVFormDev
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property integer $version
* @property string $term
* @property string $description
* @property boolean $is_hidden
* @property bigInteger $hv_company_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvFormDevItems
* @property \Illuminate\Database\Eloquent\Collection $tmSystemExams
* @property \Illuminate\Database\Eloquent\Collection $tmBuildingExams
* @property \Illuminate\Database\Eloquent\Collection $tmCCTests
*/ 
abstract class HVFormDev extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_form_dev';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'version' => 1,
        'is_hidden' => 0
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'version' => 'integer',
        'term' => 'string',
        'description' => 'string',
        'is_hidden' => 'boolean',
        'hv_company_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvFormDevItems()
    {
        return $this->hasMany('\App\Models\hv\HVFormDevItem', 'hv_form_dev_id', 'id');
    }
    
    public function tmSystemExams()
    {
        return $this->hasMany('\App\Models\tm\TMSystemExam', 'hv_form_dev_id', 'id');
    }
    
    public function tmBuildingExams()
    {
        return $this->hasMany('\App\Models\tm\TMBuildingExam', 'hv_form_dev_id', 'id');
    }
    
    public function tmCCTests()
    {
        return $this->hasMany('\App\Models\tm\TMCCTest', 'hv_form_dev_id', 'id');
    }
}
