<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVFormDevItem
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $term
* @property mediumText $content
* @property longText $description
* @property string $input_format
* @property string $output_format
* @property integer $input_len
* @property boolean $visible_in_list
* @property boolean $visible_in_detail
* @property boolean $is_hidable
* @property boolean $is_mandatory
* @property boolean $read_only
* @property boolean $is_hidden
* @property bigInteger $hv_company_id
* @property bigInteger $hv_form_dev_id
* @property bigInteger $hv_input_type_id
* @property integer $sort_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVInputType|null $hvInputType
* @property \App\Models\hv\HVFormDev|null $hvFormDev
* @property \Illuminate\Database\Eloquent\Collection $tmCCTestItems
*/ 
abstract class HVFormDevItem extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_form_dev_item';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'visible_in_list' => 1,
        'visible_in_detail' => 1,
        'is_hidable' => 1,
        'is_mandatory' => 0,
        'read_only' => 0,
        'is_hidden' => 0,
        'sort_id' => 0
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'term' => 'string',
        'content' => 'string',
        'description' => 'string',
        'input_format' => 'string',
        'output_format' => 'string',
        'input_len' => 'integer',
        'visible_in_list' => 'boolean',
        'visible_in_detail' => 'boolean',
        'is_hidable' => 'boolean',
        'is_mandatory' => 'boolean',
        'read_only' => 'boolean',
        'is_hidden' => 'boolean',
        'hv_company_id' => 'integer',
        'hv_form_dev_id' => 'integer',
        'hv_input_type_id' => 'integer',
        'sort_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvInputType()
    {
        return $this->belongsTo('\App\Models\hv\HVInputType', 'hv_input_type_id', 'id');
    }
    
    public function hvFormDev()
    {
        return $this->belongsTo('\App\Models\hv\HVFormDev', 'hv_form_dev_id', 'id');
    }
    
    public function tmCCTestItems()
    {
        return $this->hasMany('\App\Models\tm\TMCCTestItem', 'hv_form_dev_item_id', 'id');
    }
}
