<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVLog
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $context
* @property longText $log
* @property \Carbon\Carbon $created_at
*/ 
abstract class HVLog extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_log';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'context' => 'string',
        'log' => 'string',
        'created_at' => 'datetime'
    ];
}
