<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVMobileDeviceConfig
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property text $config
* @property text $notes
* @property bigInteger $hv_company_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvMobileDevices
*/ 
abstract class HVMobileDeviceConfig extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_mobile_device_config';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'config' => 'string',
        'notes' => 'string',
        'hv_company_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvMobileDevices()
    {
        return $this->hasMany('\App\Models\hv\HVMobileDevice', 'hv_mobile_device_config_id', 'id');
    }
}
