<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVMobileDevice
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $session_token
* @property \Carbon\Carbon $last_login_at
* @property \Carbon\Carbon $last_access_at
* @property \Carbon\Carbon $last_logout_at
* @property string $push_token
* @property integer $accu_level
* @property string $os
* @property string $os_version
* @property string $app_version
* @property bigInteger $hv_company_id
* @property bigInteger $hv_mobile_device_config_id
* @property bigInteger $hv_way_point_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVMobileDeviceConfig|null $hvMobileDeviceConfig
* @property \App\Models\hv\HVWayPoint|null $hvWayPoint
* @property \Illuminate\Database\Eloquent\Collection $hvUser
*/ 
abstract class HVMobileDevice extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_mobile_device';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['accu_level' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'session_token' => 'string',
        'last_login_at' => 'datetime',
        'last_access_at' => 'datetime',
        'last_logout_at' => 'datetime',
        'push_token' => 'string',
        'accu_level' => 'integer',
        'os' => 'string',
        'os_version' => 'string',
        'app_version' => 'string',
        'hv_company_id' => 'integer',
        'hv_mobile_device_config_id' => 'integer',
        'hv_way_point_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvMobileDeviceConfig()
    {
        return $this->belongsTo('\App\Models\hv\HVMobileDeviceConfig', 'hv_mobile_device_config_id', 'id');
    }
    
    public function hvWayPoint()
    {
        return $this->belongsTo('\App\Models\hv\HVWayPoint', 'hv_way_point_id', 'id');
    }
    
    public function hvUser()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_mobile_device_id', 'id');
    }
}
