<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVResourceType
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $description
* @property boolean $email_notification
* @property boolean $is_external
* @property bigInteger $hv_company_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvUsers
*/ 
abstract class HVResourceType extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_resource_type';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'email_notification' => 0,
        'is_external' => 0
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'description' => 'string',
        'email_notification' => 'boolean',
        'is_external' => 'boolean',
        'hv_company_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvUsers()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_resource_type_id', 'id');
    }
}
