<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVResourceZone
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property \Carbon\Carbon $start_at
* @property \Carbon\Carbon $end_at
* @property string $repeat_type_ident
* @property integer $interval
* @property \Carbon\Carbon $repeat_until_at
* @property bigInteger $hv_company_id
* @property bigInteger $hv_user_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVUser|null $hvUser
*/ 
abstract class HVResourceZone extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_resource_zone';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'start_at' => 'datetime',
        'end_at' => 'datetime',
        'repeat_type_ident' => 'string',
        'interval' => 'integer',
        'repeat_until_at' => 'datetime',
        'hv_company_id' => 'integer',
        'hv_user_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvUser()
    {
        return $this->belongsTo('\App\Models\hv\HVUser', 'hv_user_id', 'id');
    }
}
