<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVStateFul
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $context
* @property text $value
* @property boolean $autostart
* @property bigInteger $hv_company_id
* @property bigInteger $hv_user_id
* @property \App\Models\hv\HVUser $hvUser
*/ 
abstract class HVStateFul extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_state_ful';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['autostart' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'context' => 'string',
        'value' => 'string',
        'autostart' => 'boolean',
        'hv_company_id' => 'integer',
        'hv_user_id' => 'integer'
    ];
    
    public function hvUser()
    {
        return $this->belongsTo('\App\Models\hv\HVUser', 'hv_user_id', 'id');
    }
}
