<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVUserGroup
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property boolean $admin_access
* @property string $description
* @property longText $config
* @property bigInteger $hv_company_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $hvUsers
* @property \Illuminate\Database\Eloquent\Collection $hvUserGroupMenus
*/ 
abstract class HVUserGroup extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_user_group';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['admin_access' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'admin_access' => 'boolean',
        'description' => 'string',
        'config' => 'string',
        'hv_company_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvUsers()
    {
        return $this->hasMany('\App\Models\hv\HVUser', 'hv_user_group_id', 'id');
    }
    
    public function hvUserGroupMenus()
    {
        return $this->hasMany('\App\Models\hv\HVUserGroupMenu', 'hv_user_group_id', 'id');
    }
}
