<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVUserGroupMenu
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $menu_ident
* @property bigInteger $hv_company_id
* @property bigInteger $hv_user_group_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property \App\Models\hv\HVUserGroup|null $hvUserGroup
*/ 
abstract class HVUserGroupMenu extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_user_group_menu';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'menu_ident' => 'string',
        'hv_company_id' => 'integer',
        'hv_user_group_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime'
    ];
    
    public function hvUserGroup()
    {
        return $this->belongsTo('\App\Models\hv\HVUserGroup', 'hv_user_group_id', 'id');
    }
}
