<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVUserAutostart
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property text $modules
* @property bigInteger $hv_company_id
* @property bigInteger $hv_user_id
* @property \Carbon\Carbon $created_at
* @property \App\Models\hv\HVUser|null $hvUser
*/ 
abstract class HVUserAutostart extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_user_autostart';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'modules' => 'string',
        'hv_company_id' => 'integer',
        'hv_user_id' => 'integer',
        'created_at' => 'datetime'
    ];
    
    public function hvUser()
    {
        return $this->belongsTo('\App\Models\hv\HVUser', 'hv_user_id', 'id');
    }
}
