<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVUser
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $lastname
* @property string $firstname
* @property string $street
* @property string $zip
* @property string $city
* @property double $address_lat
* @property double $address_lon
* @property string $loginname
* @property string $password
* @property \Carbon\Carbon $password_changed_at
* @property string $nfc_ident
* @property string $qr_ident
* @property boolean $is_hidden
* @property boolean $is_superuser
* @property string $office_email
* @property string $office_email_2
* @property string $office_phone
* @property string $office_mobile
* @property boolean $web_access
* @property \Carbon\Carbon $web_access_until
* @property boolean $mobile_device_access
* @property \Carbon\Carbon $mobile_device_access_until
* @property \Carbon\Carbon $last_login_at
* @property \Carbon\Carbon $last_access_at
* @property \Carbon\Carbon $last_logout_at
* @property string $session_token
* @property string $reset_token
* @property \Carbon\Carbon $reset_token_at
* @property string $qualifications
* @property boolean $is_external
* @property boolean $use_tile_menu
* @property bigInteger $current_task_id
* @property integer $current_distance_to_task
* @property bigInteger $hv_company_id
* @property bigInteger $hv_country_id
* @property bigInteger $hv_user_group_id
* @property bigInteger $hv_company_department_id
* @property bigInteger $hv_mobile_device_id
* @property bigInteger $hv_resource_type_id
* @property bigInteger $hv_report_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVCompanyDepartment|null $hvCompanyDepartment
* @property \App\Models\hv\HVCompany $hvCompany
* @property \App\Models\hv\HVCountry|null $hvCountry
* @property \App\Models\hv\HVMobileDevice|null $hvMobileDevice
* @property \App\Models\hv\HVReport|null $hvReport
* @property \App\Models\hv\HVResourceType|null $hvResourceType
* @property \App\Models\hv\HVUserGroup|null $hvUserGroup
* @property \Illuminate\Database\Eloquent\Collection $hvStateFuls
* @property \Illuminate\Database\Eloquent\Collection $hvUserAutostarts
* @property \Illuminate\Database\Eloquent\Collection $hvWayPoints
* @property \Illuminate\Database\Eloquent\Collection $hvResourceZones
*/ 
abstract class HVUser extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_user';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'is_hidden' => 0,
        'is_superuser' => 0,
        'web_access' => 1,
        'mobile_device_access' => 0,
        'is_external' => 0,
        'use_tile_menu' => 0
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'lastname' => 'string',
        'firstname' => 'string',
        'street' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'address_lat' => 'double',
        'address_lon' => 'double',
        'loginname' => 'string',
        'password' => 'string',
        'password_changed_at' => 'datetime',
        'nfc_ident' => 'string',
        'qr_ident' => 'string',
        'is_hidden' => 'boolean',
        'is_superuser' => 'boolean',
        'office_email' => 'string',
        'office_email_2' => 'string',
        'office_phone' => 'string',
        'office_mobile' => 'string',
        'web_access' => 'boolean',
        'web_access_until' => 'datetime',
        'mobile_device_access' => 'boolean',
        'mobile_device_access_until' => 'datetime',
        'last_login_at' => 'datetime',
        'last_access_at' => 'datetime',
        'last_logout_at' => 'datetime',
        'session_token' => 'string',
        'reset_token' => 'string',
        'reset_token_at' => 'datetime',
        'qualifications' => 'string',
        'is_external' => 'boolean',
        'use_tile_menu' => 'boolean',
        'current_task_id' => 'integer',
        'current_distance_to_task' => 'integer',
        'hv_company_id' => 'integer',
        'hv_country_id' => 'integer',
        'hv_user_group_id' => 'integer',
        'hv_company_department_id' => 'integer',
        'hv_mobile_device_id' => 'integer',
        'hv_resource_type_id' => 'integer',
        'hv_report_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvCompanyDepartment()
    {
        return $this->belongsTo('\App\Models\hv\HVCompanyDepartment', 'hv_company_department_id', 'id');
    }
    
    public function hvCompany()
    {
        return $this->belongsTo('\App\Models\hv\HVCompany', 'hv_company_id', 'id');
    }
    
    public function hvCountry()
    {
        return $this->belongsTo('\App\Models\hv\HVCountry', 'hv_country_id', 'id');
    }
    
    public function hvMobileDevice()
    {
        return $this->belongsTo('\App\Models\hv\HVMobileDevice', 'hv_mobile_device_id', 'id');
    }
    
    public function hvReport()
    {
        return $this->belongsTo('\App\Models\hv\HVReport', 'hv_report_id', 'id');
    }
    
    public function hvResourceType()
    {
        return $this->belongsTo('\App\Models\hv\HVResourceType', 'hv_resource_type_id', 'id');
    }
    
    public function hvUserGroup()
    {
        return $this->belongsTo('\App\Models\hv\HVUserGroup', 'hv_user_group_id', 'id');
    }
    
    public function hvStateFuls()
    {
        return $this->hasMany('\App\Models\hv\HVStateFul', 'hv_user_id', 'id');
    }
    
    public function hvUserAutostarts()
    {
        return $this->hasMany('\App\Models\hv\HVUserAutostart', 'hv_user_id', 'id');
    }
    
    public function hvWayPoints()
    {
        return $this->hasMany('\App\Models\hv\HVWayPoint', 'hv_user_id', 'id');
    }
    
    public function hvResourceZones()
    {
        return $this->hasMany('\App\Models\hv\HVResourceZone', 'hv_user_id', 'id');
    }
}
