<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\hv\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class HVWayPoint
* @package App\Models\hv\Base
*
* @property bigInteger $id
* @property \Carbon\Carbon $location_at
* @property double $lat
* @property double $lon
* @property integer $altitude
* @property integer $speed
* @property integer $direction
* @property integer $precision
* @property integer $angle
* @property integer $distance
* @property bigInteger $hv_company_id
* @property bigInteger $hv_user_id
* @property bigInteger $hv_mobile_device_id
* @property \Carbon\Carbon $created_at
* @property \App\Models\hv\HVUser|null $hvUser
* @property \Illuminate\Database\Eloquent\Collection $hvMobileDevices
*/ 
abstract class HVWayPoint extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'hv_way_point';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'location_at' => 'datetime',
        'lat' => 'double',
        'lon' => 'double',
        'altitude' => 'integer',
        'speed' => 'integer',
        'direction' => 'integer',
        'precision' => 'integer',
        'angle' => 'integer',
        'distance' => 'integer',
        'hv_company_id' => 'integer',
        'hv_user_id' => 'integer',
        'hv_mobile_device_id' => 'integer',
        'created_at' => 'datetime'
    ];
    
    public function hvUser()
    {
        return $this->belongsTo('\App\Models\hv\HVUser', 'hv_user_id', 'id');
    }
    
    public function hvMobileDevices()
    {
        return $this->hasMany('\App\Models\hv\HVMobileDevice', 'hv_way_point_id', 'id');
    }
}
