<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 00ec4080-2710-4f9d-bb17-992e5c5fa113-02
 * Migration datetime: 2021-12-15 05:38:30.867300
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations02TmReptool2021121505383086 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('tm_building', function (Blueprint $table) {
            $table->foreign('hv_country_id')->references('id')->on('hv_country');
        });
        Schema::table('tm_service_provider', function (Blueprint $table) {
            $table->foreign('hv_country_id')->references('id')->on('hv_country');
        });
        Schema::table('tm_system_exam', function (Blueprint $table) {
            $table->foreign('hv_form_dev_id')->references('id')->on('hv_form_dev');
        });
        Schema::table('tm_building_exam', function (Blueprint $table) {
            $table->foreign('hv_form_dev_id')->references('id')->on('hv_form_dev');
        });
        Schema::table('tm_cc_test', function (Blueprint $table) {
            $table->foreign('hv_form_dev_id')->references('id')->on('hv_form_dev');
        });
        Schema::table('tm_cc_test_item', function (Blueprint $table) {
            $table->foreign('hv_form_dev_item_id')->references('id')->on('hv_form_dev_item');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('tm_cc_test_item')) {
            Schema::table('tm_cc_test_item', function (Blueprint $table) {
                $table->dropForeign(['hv_form_dev_item_id']);
            });
        }
        if (Schema::hasTable('tm_cc_test')) {
            Schema::table('tm_cc_test', function (Blueprint $table) {
                $table->dropForeign(['hv_form_dev_id']);
            });
        }
        if (Schema::hasTable('tm_building_exam')) {
            Schema::table('tm_building_exam', function (Blueprint $table) {
                $table->dropForeign(['hv_form_dev_id']);
            });
        }
        if (Schema::hasTable('tm_system_exam')) {
            Schema::table('tm_system_exam', function (Blueprint $table) {
                $table->dropForeign(['hv_form_dev_id']);
            });
        }
        if (Schema::hasTable('tm_service_provider')) {
            Schema::table('tm_service_provider', function (Blueprint $table) {
                $table->dropForeign(['hv_country_id']);
            });
        }
        if (Schema::hasTable('tm_building')) {
            Schema::table('tm_building', function (Blueprint $table) {
                $table->dropForeign(['hv_country_id']);
            });
        }
    }
}
