<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 00ec4080-2710-4f9d-bb17-992e5c5fa113-01
 * Migration datetime: 2021-12-15 05:38:30.867300
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01TmReptool2021121505383086 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tm_system', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->string('manufacturer', 60)->nullable(true);
            $table->string('model', 80)->nullable(true);
            $table->integer('construction_year')->nullable(true);
            $table->string('room', 80)->nullable(true);
            $table->string('area', 80)->nullable(true);
            $table->boolean('service_contract')->nullable(true)->default(0);
            $table->boolean('is_active')->nullable(true)->default(1);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_building_id')->nullable(true)->unsigned();
            $table->bigInteger('tm_service_provider_id')->nullable(true)->unsigned();
            $table->bigInteger('tm_service_provider_contact_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_building', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_country_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_stock', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_building_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->float('minimum_stock', 8, 2)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_item_unit_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_service_provider', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('name_1', 80)->nullable(true);
            $table->string('name_2', 80)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_country_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_item_unit', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_system_binary', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->string('filename', 240)->nullable(true);
            $table->string('filename_org', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_system_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_system_exam', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('interval')->nullable(true);
            $table->integer('warning_time')->nullable(true);
            $table->date('last_exam_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_system_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_form_dev_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_building_binary', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->string('filename', 240)->nullable(true);
            $table->string('filename_org', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_building_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_stock_storage_place', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_stock_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_service_provider_contact', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('contact_person', 80)->nullable(true);
            $table->string('function_in_operation', 80)->nullable(true);
            $table->string('contact_phone', 60)->nullable(true);
            $table->string('contact_mobile', 60)->nullable(true);
            $table->string('contact_email', 120)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_service_provider_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_building_exam', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('interval')->nullable(true);
            $table->integer('warning_time')->nullable(true);
            $table->date('last_exam_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_building_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_form_dev_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_cc_person', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('code', 30)->nullable(true);
            $table->string('lastname', 60)->nullable(true);
            $table->string('firstname', 60)->nullable(true);
            $table->string('phone', 60)->nullable(true);
            $table->string('mobile', 60)->nullable(true);
            $table->string('email', 120)->nullable(true);
            $table->string('staff_sub_section', 80)->nullable(true);
            $table->string('staff_section', 80)->nullable(true);
            $table->string('assignment', 120)->nullable(true);
            $table->date('vaccination_1_at')->nullable(true);
            $table->date('vaccination_2_at')->nullable(true);
            $table->date('vaccination_3_at')->nullable(true);
            $table->date('vaccination_4_at')->nullable(true);
            $table->date('vaccination_5_at')->nullable(true);
            $table->date('vaccination_6_at')->nullable(true);
            $table->date('vaccination_protection_at')->nullable(true);
            $table->date('recovered_at')->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->boolean('test_needed')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_cc_vaccination_status_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_cc_test', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('lastname', 60)->nullable(true);
            $table->string('firstname', 60)->nullable(true);
            $table->longText('notes')->nullable(true);
            $table->string('status_1', 20)->nullable(true);
            $table->string('status_2', 20)->nullable(true);
            $table->boolean('is_done')->nullable(true)->default(0);
            $table->dateTime('finished_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_cc_person_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_form_dev_id')->nullable(true)->unsigned();
            $table->bigInteger('tm_result_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_cc_test_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->text('value')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('tm_cc_test_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_form_dev_item_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('tm_cc_vaccination_status', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('sort_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::table('tm_system', function (Blueprint $table) {
            $table->foreign('tm_building_id')->references('id')->on('tm_building');
        });
        Schema::table('tm_system', function (Blueprint $table) {
            $table->foreign('tm_service_provider_id')->references('id')->on('tm_service_provider');
        });
        Schema::table('tm_system', function (Blueprint $table) {
            $table->foreign('tm_service_provider_contact_id')->references('id')->on('tm_service_provider_contact');
        });
        Schema::table('tm_stock', function (Blueprint $table) {
            $table->foreign('tm_building_id')->references('id')->on('tm_building');
        });
        Schema::table('tm_item', function (Blueprint $table) {
            $table->foreign('tm_item_unit_id')->references('id')->on('tm_item_unit');
        });
        Schema::table('tm_system_binary', function (Blueprint $table) {
            $table->foreign('tm_system_id')->references('id')->on('tm_system');
        });
        Schema::table('tm_system_exam', function (Blueprint $table) {
            $table->foreign('tm_system_id')->references('id')->on('tm_system');
        });
        Schema::table('tm_building_binary', function (Blueprint $table) {
            $table->foreign('tm_building_id')->references('id')->on('tm_building');
        });
        Schema::table('tm_stock_storage_place', function (Blueprint $table) {
            $table->foreign('tm_stock_id')->references('id')->on('tm_stock');
        });
        Schema::table('tm_service_provider_contact', function (Blueprint $table) {
            $table->foreign('tm_service_provider_id')->references('id')->on('tm_service_provider');
        });
        Schema::table('tm_building_exam', function (Blueprint $table) {
            $table->foreign('tm_building_id')->references('id')->on('tm_building');
        });
        Schema::table('tm_cc_person', function (Blueprint $table) {
            $table->foreign('tm_cc_vaccination_status_id')->references('id')->on('tm_cc_vaccination_status');
        });
        Schema::table('tm_cc_test', function (Blueprint $table) {
            $table->foreign('tm_cc_person_id')->references('id')->on('tm_cc_person');
        });
        Schema::table('tm_cc_test_item', function (Blueprint $table) {
            $table->foreign('tm_cc_test_id')->references('id')->on('tm_cc_test');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('tm_cc_test_item')) {
            Schema::table('tm_cc_test_item', function (Blueprint $table) {
                $table->dropForeign(['tm_cc_test_id']);
            });
        }
        if (Schema::hasTable('tm_cc_test')) {
            Schema::table('tm_cc_test', function (Blueprint $table) {
                $table->dropForeign(['tm_cc_person_id']);
            });
        }
        if (Schema::hasTable('tm_cc_person')) {
            Schema::table('tm_cc_person', function (Blueprint $table) {
                $table->dropForeign(['tm_cc_vaccination_status_id']);
            });
        }
        if (Schema::hasTable('tm_building_exam')) {
            Schema::table('tm_building_exam', function (Blueprint $table) {
                $table->dropForeign(['tm_building_id']);
            });
        }
        if (Schema::hasTable('tm_service_provider_contact')) {
            Schema::table('tm_service_provider_contact', function (Blueprint $table) {
                $table->dropForeign(['tm_service_provider_id']);
            });
        }
        if (Schema::hasTable('tm_stock_storage_place')) {
            Schema::table('tm_stock_storage_place', function (Blueprint $table) {
                $table->dropForeign(['tm_stock_id']);
            });
        }
        if (Schema::hasTable('tm_building_binary')) {
            Schema::table('tm_building_binary', function (Blueprint $table) {
                $table->dropForeign(['tm_building_id']);
            });
        }
        if (Schema::hasTable('tm_system_exam')) {
            Schema::table('tm_system_exam', function (Blueprint $table) {
                $table->dropForeign(['tm_system_id']);
            });
        }
        if (Schema::hasTable('tm_system_binary')) {
            Schema::table('tm_system_binary', function (Blueprint $table) {
                $table->dropForeign(['tm_system_id']);
            });
        }
        if (Schema::hasTable('tm_item')) {
            Schema::table('tm_item', function (Blueprint $table) {
                $table->dropForeign(['tm_item_unit_id']);
            });
        }
        if (Schema::hasTable('tm_stock')) {
            Schema::table('tm_stock', function (Blueprint $table) {
                $table->dropForeign(['tm_building_id']);
            });
        }
        if (Schema::hasTable('tm_system')) {
            Schema::table('tm_system', function (Blueprint $table) {
                $table->dropForeign(['tm_service_provider_contact_id']);
            });
        }
        if (Schema::hasTable('tm_system')) {
            Schema::table('tm_system', function (Blueprint $table) {
                $table->dropForeign(['tm_service_provider_id']);
            });
        }
        if (Schema::hasTable('tm_system')) {
            Schema::table('tm_system', function (Blueprint $table) {
                $table->dropForeign(['tm_building_id']);
            });
        }
        Schema::dropIfExists('tm_cc_vaccination_status');
        Schema::dropIfExists('tm_cc_test_item');
        Schema::dropIfExists('tm_cc_test');
        Schema::dropIfExists('tm_cc_person');
        Schema::dropIfExists('tm_building_exam');
        Schema::dropIfExists('tm_service_provider_contact');
        Schema::dropIfExists('tm_stock_storage_place');
        Schema::dropIfExists('tm_building_binary');
        Schema::dropIfExists('tm_system_exam');
        Schema::dropIfExists('tm_system_binary');
        Schema::dropIfExists('tm_item_unit');
        Schema::dropIfExists('tm_service_provider');
        Schema::dropIfExists('tm_item');
        Schema::dropIfExists('tm_stock');
        Schema::dropIfExists('tm_building');
        Schema::dropIfExists('tm_system');
    }
}
