<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 00ec4080-2710-4f9d-bb17-992e5c5fa113
 * Migration datetime: 2021-12-15 05:38:30.867300
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01TmHvBase2021121505383086 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('hv_company', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 10)->nullable(true);
            $table->string('name_1', 80)->nullable(true);
            $table->string('name_2', 80)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->string('contact_person', 80)->nullable(true);
            $table->string('contact_office_phone', 30)->nullable(true);
            $table->string('contact_office_mobile', 30)->nullable(true);
            $table->string('contact_office_email', 120)->nullable(true);
            $table->string('web', 80)->nullable(true);
            $table->dateTime('access_until')->nullable(true);
            $table->longText('config')->nullable(true);
            $table->boolean('auto_password_change')->nullable(true)->default(0);
            $table->boolean('is_master')->nullable(true);
            $table->string('domain_shortcut', 30)->nullable(true);
            $table->string('copyright_label', 80)->nullable(true);
            $table->string('favicon', 80)->nullable(true);
            $table->string('browser_title', 60)->nullable(true);
            $table->string('logo', 80)->nullable(true);
            $table->bigInteger('hv_country_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_country_id'], 'hv_company_hv_country_id_foreign');
            $table->index(['ident','access_until'], 'idx_1');
        });
        Schema::create('hv_company_department', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 80)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->string('street', 80)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->string('country_ident', 10)->nullable(true);
            $table->double('lat', 12, 7)->nullable(true);
            $table->double('lon', 12, 7)->nullable(true);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_company_menu', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('menu_ident', 40)->nullable(true);
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('hv_company_id')->nullable(true)->unsigned();
            $table->index(['hv_company_id'], 'hv_company_menu_hv_company_id_foreign');
        });
        Schema::create('hv_country', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('iso_code_1', 5)->nullable(true);
            $table->string('iso_code_2', 5)->nullable(true);
            $table->string('ident', 60)->nullable(true);
            $table->bigInteger('sort_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['ident','sort_id'], 'idx1');
        });
        Schema::create('hv_mobile_device', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 80)->nullable(true);
            $table->string('session_token', 80)->nullable(true);
            $table->timestamp('last_login_at')->nullable(true);
            $table->timestamp('last_access_at')->nullable(true);
            $table->timestamp('last_logout_at')->nullable(true);
            $table->string('push_token', 255)->nullable(true);
            $table->integer('accu_level')->nullable(true)->default(0);
            $table->string('os', 20)->nullable(true);
            $table->string('os_version', 20)->nullable(true);
            $table->string('app_version', 20)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_mobile_device_config_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_way_point_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_mobile_device_config_id'], 'hv_mobile_device_hv_mobile_device_config_id_foreign');
            $table->index(['hv_way_point_id'], 'hv_mobile_device_hv_way_point_id_foreign');
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_mobile_device_config', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 20)->nullable(true);
            $table->text('config')->nullable(true);
            $table->text('notes')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_report', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->longText('definition')->nullable(true);
            $table->string('uuid', 120)->nullable(true);
            $table->boolean('is_hidden')->nullable(true)->default(0);
            $table->boolean('is_system_report')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_resource_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 80)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->boolean('email_notification')->nullable(true)->default(0);
            $table->boolean('is_external')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_state_ful', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('context', 80)->nullable(true);
            $table->text('value')->nullable(true);
            $table->boolean('autostart')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->unsigned();
            $table->index(['hv_user_id'], 'hv_state_ful_hv_user_id_foreign');
            $table->index(['context','hv_user_id'], 'idx_1');
        });
        Schema::create('hv_user', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 30)->nullable(true);
            $table->string('lastname', 60)->nullable(true);
            $table->string('firstname', 60)->nullable(true);
            $table->string('street', 80)->nullable(true);
            $table->string('zip', 10)->nullable(true);
            $table->string('city', 80)->nullable(true);
            $table->double('address_lat', 12, 7)->nullable(true);
            $table->double('address_lon', 12, 7)->nullable(true);
            $table->string('loginname', 20)->nullable(true);
            $table->string('password', 20)->nullable(true);
            $table->dateTime('password_changed_at')->nullable(true);
            $table->string('nfc_ident', 255)->nullable(true);
            $table->string('qr_ident', 255)->nullable(true);
            $table->boolean('is_hidden')->nullable(true)->default(0)->unsigned();
            $table->boolean('is_superuser')->nullable(true)->default(0)->unsigned();
            $table->string('office_email', 80)->nullable(true);
            $table->string('office_email_2', 80)->nullable(true);
            $table->string('office_phone', 80)->nullable(true);
            $table->string('office_mobile', 80)->nullable(true);
            $table->boolean('web_access')->nullable(true)->default(1)->unsigned();
            $table->dateTime('web_access_until')->nullable(true);
            $table->boolean('mobile_device_access')->nullable(true)->default(0)->unsigned();
            $table->dateTime('mobile_device_access_until')->nullable(true);
            $table->timestamp('last_login_at')->nullable(true);
            $table->timestamp('last_access_at')->nullable(true);
            $table->timestamp('last_logout_at')->nullable(true);
            $table->string('session_token', 80)->nullable(true);
            $table->string('reset_token', 80)->nullable(true);
            $table->dateTime('reset_token_at')->nullable(true);
            $table->string('qualifications', 250)->nullable(true);
            $table->boolean('is_external')->nullable(true)->default(0);
            $table->boolean('use_tile_menu')->nullable(true)->default(0);
            $table->bigInteger('current_task_id')->nullable(true);
            $table->integer('current_distance_to_task')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_country_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_user_group_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_company_department_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_mobile_device_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_resource_type_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_report_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_department_id'], 'hv_user_hv_company_department_id_foreign');
            $table->index(['hv_country_id'], 'hv_user_hv_country_id_foreign');
            $table->unique(['hv_mobile_device_id'], 'hv_user_hv_mobile_device_id_unique');
            $table->index(['hv_report_id'], 'hv_user_hv_report_id_foreign');
            $table->index(['hv_resource_type_id'], 'hv_user_hv_resource_type_id_foreign');
            $table->index(['hv_user_group_id'], 'hv_user_hv_user_group_id_foreign');
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_user_autostart', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->text('modules')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->index(['hv_user_id'], 'hv_user_autostart_hv_user_id_foreign');
        });
        Schema::create('hv_user_group', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->boolean('admin_access')->nullable(true)->default(0)->unsigned();
            $table->string('description', 240)->nullable(true);
            $table->longText('config')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_user_group_menu', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('menu_ident', 40)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_group_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->index(['hv_user_group_id'], 'hv_user_group_menu_hv_user_group_id_foreign');
            $table->index(['hv_company_id'], 'idx_1');
        });
        Schema::create('hv_way_point', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->timestamp('location_at')->nullable(true);
            $table->double('lat', 12, 7)->nullable(true);
            $table->double('lon', 12, 7)->nullable(true);
            $table->integer('altitude')->nullable(true);
            $table->integer('speed')->nullable(true);
            $table->integer('direction')->nullable(true);
            $table->integer('precision')->nullable(true);
            $table->integer('angle')->nullable(true);
            $table->integer('distance')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_mobile_device_id')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->index(['hv_mobile_device_id'], 'hv_way_point_hv_mobile_device_id_foreign');
            $table->index(['hv_user_id'], 'hv_way_point_hv_user_id_foreign');
            $table->index(['hv_company_id'], 'idx_1');
            $table->index(['location_at','hv_user_id'], 'idx_2');
        });
        Schema::create('hv_qualification', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->string('description', 240)->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_input_type', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 120)->nullable(true);
            $table->longText('description')->nullable(true);
            $table->integer('sort_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_resource_zone', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->timestamp('start_at')->nullable(true);
            $table->timestamp('end_at')->nullable(true);
            $table->string('repeat_type_ident', 30)->nullable(true);
            $table->integer('interval')->nullable(true);
            $table->timestamp('repeat_until_at')->nullable(true);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_user_id')->nullable(true)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_form_dev', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('ident', 60)->nullable(true);
            $table->integer('version')->nullable(true)->default(1);
            $table->string('term', 120)->nullable(true);
            $table->string('description', 512)->nullable(true);
            $table->boolean('is_hidden')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_form_dev_item', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('term', 120)->nullable(true);
            $table->mediumText('content')->nullable(true);
            $table->longText('description')->nullable(true);
            $table->string('input_format', 20)->nullable(true);
            $table->string('output_format', 20)->nullable(true);
            $table->integer('input_len')->nullable(true)->unsigned();
            $table->boolean('visible_in_list')->nullable(true)->default(1);
            $table->boolean('visible_in_detail')->nullable(true)->default(1);
            $table->boolean('is_hidable')->nullable(true)->default(1);
            $table->boolean('is_mandatory')->nullable(true)->default(0);
            $table->boolean('read_only')->nullable(true)->default(0);
            $table->boolean('is_hidden')->nullable(true)->default(0);
            $table->bigInteger('hv_company_id')->unsigned();
            $table->bigInteger('hv_form_dev_id')->nullable(true)->unsigned();
            $table->bigInteger('hv_input_type_id')->nullable(true)->unsigned();
            $table->integer('sort_id')->nullable(true)->default(0)->unsigned();
            $table->bigInteger('created_by')->nullable(true)->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->bigInteger('updated_by')->nullable(true)->unsigned();
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('hv_log', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('context', 60)->nullable(true);
            $table->longText('log')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->index(['created_at','context'], 'idx_1');
        });
        Schema::table('hv_company', function (Blueprint $table) {
            $table->foreign('hv_country_id')->references('id')->on('hv_country')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_company_menu', function (Blueprint $table) {
            $table->foreign('hv_company_id')->references('id')->on('hv_company')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_mobile_device', function (Blueprint $table) {
            $table->foreign('hv_mobile_device_config_id')->references('id')->on('hv_mobile_device_config')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_mobile_device', function (Blueprint $table) {
            $table->foreign('hv_way_point_id')->references('id')->on('hv_way_point')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_state_ful', function (Blueprint $table) {
            $table->foreign('hv_user_id')->references('id')->on('hv_user')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_company_department_id')->references('id')->on('hv_company_department')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_company_id')->references('id')->on('hv_company')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_country_id')->references('id')->on('hv_country')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_mobile_device_id')->references('id')->on('hv_mobile_device')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_report_id')->references('id')->on('hv_report')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_resource_type_id')->references('id')->on('hv_resource_type')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user', function (Blueprint $table) {
            $table->foreign('hv_user_group_id')->references('id')->on('hv_user_group')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user_autostart', function (Blueprint $table) {
            $table->foreign('hv_user_id')->references('id')->on('hv_user')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_user_group_menu', function (Blueprint $table) {
            $table->foreign('hv_user_group_id')->references('id')->on('hv_user_group')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_way_point', function (Blueprint $table) {
            $table->foreign('hv_user_id')->references('id')->on('hv_user')->onDelete('NO ACTION')->onUpdate('NO ACTION');
        });
        Schema::table('hv_resource_zone', function (Blueprint $table) {
            $table->foreign('hv_user_id')->references('id')->on('hv_user')->onDelete('RESTRICT')->onUpdate('RESTRICT');
        });
        Schema::table('hv_form_dev_item', function (Blueprint $table) {
            $table->foreign('hv_input_type_id')->references('id')->on('hv_input_type');
        });
        Schema::table('hv_form_dev_item', function (Blueprint $table) {
            $table->foreign('hv_form_dev_id')->references('id')->on('hv_form_dev');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('hv_form_dev_item')) {
            Schema::table('hv_form_dev_item', function (Blueprint $table) {
                $table->dropForeign(['hv_form_dev_id']);
            });
        }
        if (Schema::hasTable('hv_form_dev_item')) {
            Schema::table('hv_form_dev_item', function (Blueprint $table) {
                $table->dropForeign(['hv_input_type_id']);
            });
        }
        if (Schema::hasTable('hv_resource_zone')) {
            Schema::table('hv_resource_zone', function (Blueprint $table) {
                $table->dropForeign(['hv_user_id']);
            });
        }
        if (Schema::hasTable('hv_way_point')) {
            Schema::table('hv_way_point', function (Blueprint $table) {
                $table->dropForeign(['hv_user_id']);
            });
        }
        if (Schema::hasTable('hv_user_group_menu')) {
            Schema::table('hv_user_group_menu', function (Blueprint $table) {
                $table->dropForeign(['hv_user_group_id']);
            });
        }
        if (Schema::hasTable('hv_user_autostart')) {
            Schema::table('hv_user_autostart', function (Blueprint $table) {
                $table->dropForeign(['hv_user_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_user_group_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_resource_type_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_report_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_mobile_device_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_country_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_company_id']);
            });
        }
        if (Schema::hasTable('hv_user')) {
            Schema::table('hv_user', function (Blueprint $table) {
                $table->dropForeign(['hv_company_department_id']);
            });
        }
        if (Schema::hasTable('hv_state_ful')) {
            Schema::table('hv_state_ful', function (Blueprint $table) {
                $table->dropForeign(['hv_user_id']);
            });
        }
        if (Schema::hasTable('hv_mobile_device')) {
            Schema::table('hv_mobile_device', function (Blueprint $table) {
                $table->dropForeign(['hv_way_point_id']);
            });
        }
        if (Schema::hasTable('hv_mobile_device')) {
            Schema::table('hv_mobile_device', function (Blueprint $table) {
                $table->dropForeign(['hv_mobile_device_config_id']);
            });
        }
        if (Schema::hasTable('hv_company_menu')) {
            Schema::table('hv_company_menu', function (Blueprint $table) {
                $table->dropForeign(['hv_company_id']);
            });
        }
        if (Schema::hasTable('hv_company')) {
            Schema::table('hv_company', function (Blueprint $table) {
                $table->dropForeign(['hv_country_id']);
            });
        }
        Schema::dropIfExists('hv_log');
        Schema::dropIfExists('hv_form_dev_item');
        Schema::dropIfExists('hv_form_dev');
        Schema::dropIfExists('hv_resource_zone');
        Schema::dropIfExists('hv_input_type');
        Schema::dropIfExists('hv_qualification');
        Schema::dropIfExists('hv_way_point');
        Schema::dropIfExists('hv_user_group_menu');
        Schema::dropIfExists('hv_user_group');
        Schema::dropIfExists('hv_user_autostart');
        Schema::dropIfExists('hv_user');
        Schema::dropIfExists('hv_state_ful');
        Schema::dropIfExists('hv_resource_type');
        Schema::dropIfExists('hv_report');
        Schema::dropIfExists('hv_mobile_device_config');
        Schema::dropIfExists('hv_mobile_device');
        Schema::dropIfExists('hv_country');
        Schema::dropIfExists('hv_company_menu');
        Schema::dropIfExists('hv_company_department');
        Schema::dropIfExists('hv_company');
    }
}
