<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMBuildingBinary
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $term
* @property string $filename
* @property string $filename_org
* @property bigInteger $hv_company_id
* @property bigInteger $tm_building_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMBuilding|null $tmBuilding
*/ 
abstract class TMBuildingBinary extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_building_binary';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'term' => 'string',
        'filename' => 'string',
        'filename_org' => 'string',
        'hv_company_id' => 'integer',
        'tm_building_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmBuilding()
    {
        return $this->belongsTo('\App\Models\tm\TMBuilding', 'tm_building_id', 'id');
    }
}
