<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMBuilding
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $term
* @property string $description
* @property string $street
* @property string $zip
* @property string $city
* @property bigInteger $hv_company_id
* @property bigInteger $hv_country_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVCountry|null $hvCountry
* @property \Illuminate\Database\Eloquent\Collection $tmSystems
* @property \Illuminate\Database\Eloquent\Collection $tmStocks
* @property \Illuminate\Database\Eloquent\Collection $tmBuildingBinaries
* @property \Illuminate\Database\Eloquent\Collection $tmBuildingExams
*/ 
abstract class TMBuilding extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_building';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'term' => 'string',
        'description' => 'string',
        'street' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'hv_company_id' => 'integer',
        'hv_country_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function hvCountry()
    {
        return $this->belongsTo('\App\Models\hv\HVCountry', 'hv_country_id', 'id');
    }
    
    public function tmSystems()
    {
        return $this->hasMany('\App\Models\tm\TMSystem', 'tm_building_id', 'id');
    }
    
    public function tmStocks()
    {
        return $this->hasMany('\App\Models\tm\TMStock', 'tm_building_id', 'id');
    }
    
    public function tmBuildingBinaries()
    {
        return $this->hasMany('\App\Models\tm\TMBuildingBinary', 'tm_building_id', 'id');
    }
    
    public function tmBuildingExams()
    {
        return $this->hasMany('\App\Models\tm\TMBuildingExam', 'tm_building_id', 'id');
    }
}
