<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMCCPerson
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $code
* @property string $lastname
* @property string $firstname
* @property string $phone
* @property string $mobile
* @property string $email
* @property string $staff_sub_section
* @property string $staff_section
* @property string $assignment
* @property \Carbon\Carbon $vaccination_1_at
* @property \Carbon\Carbon $vaccination_2_at
* @property \Carbon\Carbon $vaccination_3_at
* @property \Carbon\Carbon $vaccination_4_at
* @property \Carbon\Carbon $vaccination_5_at
* @property \Carbon\Carbon $vaccination_6_at
* @property \Carbon\Carbon $vaccination_protection_at
* @property \Carbon\Carbon $recovered_at
* @property longText $notes
* @property boolean $test_needed
* @property bigInteger $hv_company_id
* @property bigInteger $tm_cc_vaccination_status_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMCCVaccinationStatus|null $tmCCVaccinationStatus
* @property \Illuminate\Database\Eloquent\Collection $tmCCTests
*/ 
abstract class TMCCPerson extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_cc_person';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['test_needed' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'code' => 'string',
        'lastname' => 'string',
        'firstname' => 'string',
        'phone' => 'string',
        'mobile' => 'string',
        'email' => 'string',
        'staff_sub_section' => 'string',
        'staff_section' => 'string',
        'assignment' => 'string',
        'vaccination_1_at' => 'datetime:Y-m-d',
        'vaccination_2_at' => 'datetime:Y-m-d',
        'vaccination_3_at' => 'datetime:Y-m-d',
        'vaccination_4_at' => 'datetime:Y-m-d',
        'vaccination_5_at' => 'datetime:Y-m-d',
        'vaccination_6_at' => 'datetime:Y-m-d',
        'vaccination_protection_at' => 'datetime:Y-m-d',
        'recovered_at' => 'datetime:Y-m-d',
        'notes' => 'string',
        'test_needed' => 'boolean',
        'hv_company_id' => 'integer',
        'tm_cc_vaccination_status_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmCCVaccinationStatus()
    {
        return $this->belongsTo('\App\Models\tm\TMCCVaccinationStatus', 'tm_cc_vaccination_status_id', 'id');
    }
    
    public function tmCCTests()
    {
        return $this->hasMany('\App\Models\tm\TMCCTest', 'tm_cc_person_id', 'id');
    }
}
