<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMCCTestItem
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property text $value
* @property bigInteger $hv_company_id
* @property bigInteger $tm_cc_test_id
* @property bigInteger $hv_form_dev_item_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMCCTest|null $tmCCTest
* @property \App\Models\hv\HVFormDevItem|null $hvFormDevItem
*/ 
abstract class TMCCTestItem extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_cc_test_item';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'value' => 'string',
        'hv_company_id' => 'integer',
        'tm_cc_test_id' => 'integer',
        'hv_form_dev_item_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmCCTest()
    {
        return $this->belongsTo('\App\Models\tm\TMCCTest', 'tm_cc_test_id', 'id');
    }
    
    public function hvFormDevItem()
    {
        return $this->belongsTo('\App\Models\hv\HVFormDevItem', 'hv_form_dev_item_id', 'id');
    }
}
