<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMCCTest
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $lastname
* @property string $firstname
* @property longText $notes
* @property string $status_1
* @property string $status_2
* @property boolean $is_done
* @property \Carbon\Carbon $finished_at
* @property bigInteger $hv_company_id
* @property bigInteger $tm_cc_person_id
* @property bigInteger $hv_form_dev_id
* @property bigInteger $tm_result_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMCCPerson|null $tmCCPerson
* @property \App\Models\hv\HVFormDev|null $hvFormDev
* @property \Illuminate\Database\Eloquent\Collection $tmCCTestItems
*/ 
abstract class TMCCTest extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_cc_test';
    
    /**  
     * Specify how timestamps are stored in database and Json
     * 
     * @var string
     */
    protected $dateFormat = 'Y-m-d H:i:s';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['is_done' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'lastname' => 'string',
        'firstname' => 'string',
        'notes' => 'string',
        'status_1' => 'string',
        'status_2' => 'string',
        'is_done' => 'boolean',
        'finished_at' => 'datetime',
        'hv_company_id' => 'integer',
        'tm_cc_person_id' => 'integer',
        'hv_form_dev_id' => 'integer',
        'tm_result_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmCCPerson()
    {
        return $this->belongsTo('\App\Models\tm\TMCCPerson', 'tm_cc_person_id', 'id');
    }
    
    public function hvFormDev()
    {
        return $this->belongsTo('\App\Models\hv\HVFormDev', 'hv_form_dev_id', 'id');
    }
    
    public function tmCCTestItems()
    {
        return $this->hasMany('\App\Models\tm\TMCCTestItem', 'tm_cc_test_id', 'id');
    }
}
