<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMItem
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $term
* @property string $description
* @property float $minimum_stock
* @property bigInteger $hv_company_id
* @property bigInteger $tm_item_unit_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMItemUnit|null $tmItemUnit
*/ 
abstract class TMItem extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_item';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'term' => 'string',
        'description' => 'string',
        'minimum_stock' => 'float',
        'hv_company_id' => 'integer',
        'tm_item_unit_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmItemUnit()
    {
        return $this->belongsTo('\App\Models\tm\TMItemUnit', 'tm_item_unit_id', 'id');
    }
}
