<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMServiceProvider
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $name_1
* @property string $name_2
* @property string $street
* @property string $zip
* @property string $city
* @property bigInteger $hv_company_id
* @property bigInteger $hv_country_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\hv\HVCountry|null $HVCountry
* @property \Illuminate\Database\Eloquent\Collection $tmSystems
* @property \Illuminate\Database\Eloquent\Collection $tmServiceProviderContacts
*/ 
abstract class TMServiceProvider extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_service_provider';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'name_1' => 'string',
        'name_2' => 'string',
        'street' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'hv_company_id' => 'integer',
        'hv_country_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function HVCountry()
    {
        return $this->belongsTo('\App\Models\hv\HVCountry', 'hv_country_id', 'id');
    }
    
    public function tmSystems()
    {
        return $this->hasMany('\App\Models\tm\TMSystem', 'tm_service_provider_id', 'id');
    }
    
    public function tmServiceProviderContacts()
    {
        return $this->hasMany('\App\Models\tm\TMServiceProviderContact', 'tm_service_provider_id', 'id');
    }
}
