<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMServiceProviderContact
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $contact_person
* @property string $function_in_operation
* @property string $contact_phone
* @property string $contact_mobile
* @property string $contact_email
* @property bigInteger $hv_company_id
* @property bigInteger $tm_service_provider_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMServiceProvider|null $tmServiceProvider
* @property \Illuminate\Database\Eloquent\Collection $tmSystems
*/ 
abstract class TMServiceProviderContact extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_service_provider_contact';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'contact_person' => 'string',
        'function_in_operation' => 'string',
        'contact_phone' => 'string',
        'contact_mobile' => 'string',
        'contact_email' => 'string',
        'hv_company_id' => 'integer',
        'tm_service_provider_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmServiceProvider()
    {
        return $this->belongsTo('\App\Models\tm\TMServiceProvider', 'tm_service_provider_id', 'id');
    }
    
    public function tmSystems()
    {
        return $this->hasMany('\App\Models\tm\TMSystem', 'tm_service_provider_contact_id', 'id');
    }
}
