<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\tm\Base;

use Illuminate\Database\Eloquent\Model;

/**
* Class TMSystem
* @package App\Models\tm\Base
*
* @property bigInteger $id
* @property string $ident
* @property string $term
* @property string $description
* @property string $manufacturer
* @property string $model
* @property integer $construction_year
* @property string $room
* @property string $area
* @property boolean $service_contract
* @property boolean $is_active
* @property bigInteger $hv_company_id
* @property bigInteger $tm_building_id
* @property bigInteger $tm_service_provider_id
* @property bigInteger $tm_service_provider_contact_id
* @property bigInteger $created_by
* @property \Carbon\Carbon $created_at
* @property bigInteger $updated_by
* @property \Carbon\Carbon $updated_at
* @property \App\Models\tm\TMBuilding|null $tmBuilding
* @property \App\Models\tm\TMServiceProvider|null $tmServiceProvider
* @property \App\Models\tm\TMServiceProviderContact|null $tmServiceProviderContact
* @property \Illuminate\Database\Eloquent\Collection $tmSystemBinaries
* @property \Illuminate\Database\Eloquent\Collection $tmSystemExams
*/ 
abstract class TMSystem extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'tm_system';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'service_contract' => 0,
        'is_active' => 1
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ident' => 'string',
        'term' => 'string',
        'description' => 'string',
        'manufacturer' => 'string',
        'model' => 'string',
        'construction_year' => 'integer',
        'room' => 'string',
        'area' => 'string',
        'service_contract' => 'boolean',
        'is_active' => 'boolean',
        'hv_company_id' => 'integer',
        'tm_building_id' => 'integer',
        'tm_service_provider_id' => 'integer',
        'tm_service_provider_contact_id' => 'integer',
        'created_by' => 'integer',
        'created_at' => 'datetime',
        'updated_by' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function tmBuilding()
    {
        return $this->belongsTo('\App\Models\tm\TMBuilding', 'tm_building_id', 'id');
    }
    
    public function tmServiceProvider()
    {
        return $this->belongsTo('\App\Models\tm\TMServiceProvider', 'tm_service_provider_id', 'id');
    }
    
    public function tmServiceProviderContact()
    {
        return $this->belongsTo('\App\Models\tm\TMServiceProviderContact', 'tm_service_provider_contact_id', 'id');
    }
    
    public function tmSystemBinaries()
    {
        return $this->hasMany('\App\Models\tm\TMSystemBinary', 'tm_system_id', 'id');
    }
    
    public function tmSystemExams()
    {
        return $this->hasMany('\App\Models\tm\TMSystemExam', 'tm_system_id', 'id');
    }
}
